#define TP this_player()
#define TO this_object()
#define ENV environment
#define ENVTO ENV(TO)
#define NOTME TP != ENVTO
#define RN query_real_name()
#define TPRN TP->RN
#define TPN TP->query_name()
#define TE tell_object
#define GOB "/players/wicket/guild/gob.c"
#define GID "wicket_element_orb"
#define CHAN_NAME 	"Elementalist"
#define CHAND 		"/bin/channel_daemon.c"
#define CHATOB "/players/wicket/guild/objs/chatob.c"
#define HALLPATH "/players/wicket/guild/hall/"
#define HALLRMS  "/players/wicket/guild/hall/rooms/"
#define HALLNPC  "/players/wicket/guild/hall/mobs/"
#define HELPPATH "/players/wicket/guild/help/"
#define LOGPATH  "/players/wicket/guild/logs/"
#define MEMPATH  "players/wicket/guild/members/"
#define BOOKPATH "players/wicket/guild/members/book/"
#define OBJECTPATH "/players/wicket/guild/objs/"
#define SPELLPATH "/players/wicket/guild/spells/"
#define DJINNPATH "/players/wicket/guild/spells/djinns/"
#define AIRDAEMON "/players/wicket/guild/daemons/air_daemon.c"
#define FIREDAEMON "/players/wicket/guild/daemons/fire_daemon.c"
#define EARTHDAEMON "/players/wicket/guild/daemons/earth_daemon.c"
#define WATERDAEMON "/players/wicket/guild/daemons/water_daemon.c"
#define BOOKOBJ "/players/wicket/guild/objs/book.c"
#define FREEXP User->query_free_exp()
#define COL1_SIZE 31
#define INFUSE_LIMIT (((9*level) + (9*ex_lv/4))/2)
#define GLVL1COST 0
#define GLVL2COST 250000
#define GLVL3COST 500000
#define GLVL4COST 1000000
#define GLVL5COST 2000000
#define GLVL6COST 3000000
#define GLVL7COST 5000000
