#define BASE    "/players/balowski/std/base"
#define CLEANUP "/players/balowski/std/cleanup"
#define OBJECT  "/players/balowski/std/object"
#define ARMOUR  "/players/balowski/std/armour"
#define WEAPON  "/players/balowski/std/weapon"
#define BBOARD  "/players/balowski/std/board2"
#define EDITOR  "/players/balowski/std/editor"
#define LIVING	"/players/balowski/std/work/living"
#define MONSTER "/players/balowski/std/work/monster"
#define PORTHEAL "/players/balowski/std/portheal"
#define COLOUR	"/players/balowski/std/colour"
#define ROOM    "/players/balowski/std/random/room"
#define ATMOS	"/players/balowski/std/random/atmos"
#define EXITS	"/players/balowski/std/random/exits"
#define PROPS	"/players/balowski/std/random/props"
#define SIGNS	"/players/balowski/std/random/signs"
#define GENERATE "/players/balowski/std/random/generate"

#ifndef __VERSION__
#include "std/portable.h"
#endif
