#include <kernel.h>

inherit "basic/create";
inherit ACCESS;

mixed *syllables;

void create() {
  unguarded(1, #'restore_object, "/save/names");
}

mixed *query_syllables() {
  return syllables;
}

void add_syllables (string new, int depth) {
  syllables[depth] += ({ new });
}

string random_name() {
  string *s;
  int i;
  s = allocate(2+random(2));
  s[0] = syllables[0][random(sizeof(syllables[0]))];
  s[<1] = syllables[2][random(sizeof(syllables[2]))];
  for (i=1; i<sizeof(s)-1; i++)
    s[i] = syllables[1][random(sizeof(syllables[1]))];
  return implode(s,"");
}

private static mapping not_natural_names;

status is_natural_name(string name) {
  mixed h;
  if (!not_natural_names)
    not_natural_names = ([ "aeon",
                           "african swallow",
                           "air elemental",
                           "albino alligator",
                           "alligator",
                           "another dancing skeleton",
                           "ant",
                           "ant lion",
                           "antelope",
                           "ape",
                           "apprentice",
                           "armour thrull",
                           "assassin",
                           "astereater",
                           "attentive rabbit",
                           "azure dragon",
                           "baby",
                           "baby ape",
                           "baby bat",
                           "baby bear",
                           "baby bug",
                           "baby cat",
                           "baby cow",
                           "baby dragon",
                           "baby fox",
                           "baby gnome",
                           "baby lion",
                           "baby oak",
                           "baby orc",
                           "baby rat",
                           "baby snake",
                           "baby spider",
                           "baby tiger",
                           "baby unicorn",
                           "baby wolf",
                           "baby woodelf",
                           "babydragon",
                           "babyorc",
                           "bad knight",
                           "bad thief",
                           "badger",
                           "bailiff",
                           "balrog",
                           "bandit",
                           "banshee",
                           "barkeeper",
                           "basal thrull",
                           "bass-player",
                           "bat",
                           "batrachian",
                           "bear",
                           "beast",
                           "beauty",
                           "bedbug",
                           "bee",
                           "beggar",
                           "big bad wolf",
                           "big crocodile",
                           "big dog",
                           "big mole",
                           "big pirate",
                           "big sardine",
                           "big smelly pirate",
                           "big thief",
                           "big tough guard",
                           "bigger pirate",
                           "bigger tougher guard",
                           "bird",
                           "black cat",
                           "black knight",
                           "black mouse",
                           "black rat",
                           "black reaver",
                           "black scorpion",
                           "black tulip",
                           "black wolf",
                           "block knight",
                           "blood and thunder prophet",
                           "bloodworm",
                           "blopp",
                           "blue tulip",
                           "boa constrictor",
                           "boar",
                           "bodyguard",
                           "bonsai oak",
                           "bookkeeper",
                           "bookworm",
                           "bootlegger",
                           "boring prophet",
                           "boy",
                           "bralrog",
                           "breeding pit",
                           "brown rat",
                           "brown tulip",
                           "bull",
                           "busily working brownie",
                           "butler",
                           "butterfly",
                           "buttler",  // misspelled but in use
                           "cactus",
                           "canalligator",
                           "candy seller",
                           "captain",
                           "carpenter",
                           "cat",
                           "catcher",
                           "catton",
                           "cavespider",
                           "cellar monster",
                           "centipede",
                           "champion",
                           "chaosdemon",
                           "chest",
                           "chicken",
                           "chief",
                           "chieftain",
                           "child",
                           "children",
                           "chimpanzee",
                           "choir",
                           "christmas tree monster",
                           "city guard",
                           "clerk",
                           "clesetial dragon",
                           "cloud giant",
                           "cloud of bats",
                           "cloudmover",
                           "coconut palm",
                           "completely drunk pirate",
                           "compost heap",
                           "cook",
                           "cow",
                           "creature",
                           "crocodile",
                           "crocoking",
                           "crowd",
                           "crying witch",
                           "crystal_spy",
                           "cuttlefish",
                           "daisy",
                           "dancer",
                           "dancing skeleton",
                           "dark naga",
                           "demon",
                           "demonic oak",
                           "demoon",
                           "devil",
                           "dingo",
                           "dino",
                           "dinosaur",
                           "director",
                           "disgusting pirate",
                           "displacer beast",
                           "doctor",
                           "dog",
                           "draconian guard",
                           "dragon",
                           "dragon-fly",
                           "dragonguard",
                           "drinking skeleton",
                           "drummer",
                           "drunkard",
                           "drunken dwarf",
                           "drunkenteddy",
                           "dwarf",
                           "dwarven outlaw",
                           "dwarves",
                           "eagle",
                           "earth elemental",
                           "eater",
                           "eating rabbit",
                           "echo",
                           "efreet",
                           "eldritch vapor",
                           "elephant",
                           "elf",
                           "elf zombie",
                           "elfboy",
                           "elfking",
                           "elfwarrior",
                           "emu",
                           "english castle ghost",
                           "enormous crocodile",
                           "escoryn city guard",
                           "european swallow",
                           "evil bandit",
                           "evil earthworm",
                           "evil knight",
                           "evil pirate",
                           "evil sirpit",
                           "ex-leper",
                           "falameezar",
                           "falcon",
                           "false prophet",
                           "fat pirate",
                           "fiend",
                           "fimir",
                           "fire elemental",
                           "fireelemental",
                           "firefly",
                           "firesalamander",
                           "fish",
                           "flies",
                           "fly",
                           "fog-demon",
                           "fomor",
                           "foobar",
                           "forest troll",
                           "fox",
                           "frog",
                           "furball",
                           "furious knight",
                           "gardener",
                           "gargoyle",
                           "gatekeeper",
                           "gentleman",
                           "ghost",
                           "ghost of shido",
                           "ghoul",
                           "giant",
                           "giant crocodile",
                           "giant mole",
                           "giant octopus",
                           "giant rat",
                           "giant stainless steel dragon",
                           "giant-ant",
                           "gigantic tentacle",
                           "giraffe",
                           "girl",
                           "gladiator",
                           "glowworm",
                           "gnat",
                           "gnome",
                           "goblin",
                           "goblinbaby",
                           "goblinchief",
                           "golem",
                           "golem guard",
                           "golem-padrone",
                           "goose",
                           "gorgon",
                           "gork",
                           "grass",
                           "greedy bandit",
                           "greedy pirate",
                           "green dragon",
                           "green frog",
                           "greenish frog",
                           "greenone",
                           "grey wolf",
                           "grizzly",
                           "guard",
                           "guardteddy",
                           "guardwitch",
                           "guider",
                           "hag",
                           "half-finished monster",
                           "happy witch",
                           "haunt",
                           "hawk",
                           "headless",
                           "healer",
                           "heating demon",
                           "hedge",
                           "hedgehog",
                           "hemp plant",
                           "hippopotamus",
                           "hobgoblin",
                           "hooligans",
                           "horse",
                           "hound",
                           "huge bear",
                           "huge grey wolf",
                           "huge rat",
                           "huge spider",
                           "huge tentacle",
                           "huge werewolf",
                           "human",
                           "human bean",
                           "hummerhorn",
                           "hungry knight",
                           "hungry pirate",
                           "huorn",
                           "hydra",
                           "hyena",
                           "illness",
			   "imp",
                           "indescribable monster",
                           "inn-sewer-ant",
                           "invisible castle mover",
                           "iolo_yard_stealing_cat",
                           "island fish Jasconius",
                           "jabberwocky",
                           "jailer",
                           "kangaroo",
                           "keeper",
                           "kid",
                           "kidlion",
                           "killer bee",
                           "king",
                           "knight",
                           "koala",
                           "kobold",
                           "kookaburra",
                           "kung-fu cook",
                           "lamb",
                           "large bat",
                           "large tentacle",
                           "lark",
                           "laughsome creature",
                           "lavaworm",
                           "lazy pirate",
                           "leader",
                           "leeches",
                           "leghorn",
                           "lemmings",
                           "leper",
                           "levitating demon",
                           "librarian",
                           "linch",
                           "lion",
                           "lioness",
                           "listeners",
                           "listening skeleton",
                           "little ghost",
                           "lost soul",
                           "lumberjack",
                           "lurker",
                           "lynx",
                           "maelstorm",
                           "magician",
                           "magpie",
                           "man",
                           "manservant",
                           "marilith",
                           "marmot",
                           "maze guard",
                           "mean bandit",
                           "merfolk assassin",
                           "mermaid",
                           "millipede",
                           "mindstab thrull",
                           "minotaur",
                           "mistreated tree",
                           "moderately drunk pirate",
                           "mole",
                           "mole king",
                           "mole prince",
                           "mom",
                           "monk",
                           "monkey",
                           "monster", // Sunblood, 10-Jun-99
                           "monumental tentacle",
                           "moonman",
                           "moonworm",
                           "moorhen",
                           "more drunk pirate",
                           "mosquito",
                           "mosquitos",
                           "mouse",
                           "mouse-kid",
                           "mouth",
                           "mower",
                           "mummy",
                           "musical skeleton",
                           "naga",
                           "native",
                           "necrite",
                           "necromancer",
                           "nightmare",
                           "no-name solamnia monster",
                           "no-name wurk monster",
                           "notify_demon",
                           "nurse",
                           "oak",
                           "octopus",
                           "oger",
                           "old frog",
                           "old man",
                           "old monster",
                           "old mystic",
                           "old woman",
                           "old witch",
                           "oldman",
                           "olog",
                           "one-eyed dog",
                           "orc",
                           "orcish cook",
                           "orcish orc",
                           "outlaw",
                           "owl",
                           "papi",
                           "parkdove",
                           "peacock",
                           "peer",
                           "penguin",
                           "people",
                           "perverted pirate",
                           "phantom monster",
                           "piercer",
                           "pike",
                           "pilot",
                           "pink tulip",
                           "pirate king",
                           "pit fiend",
                           "platypus",
                           "player",
                           "poacher",
                           "polar bear",
                           "police sergeant",
                           "policeman",
                           "poor tortured woman",
                           "poor wizward",
                           "porter",
                           "potter",
                           "president",
                           "priest",
                           "quokka",
                           "rabbit",
                           "raincloud",
                           "rakshasa",
                           "ram",
                           "ranger",
                           "rat",
                           "rats",
                           "raven",
                           "really huge spider",
                           "reaper",
                           "red dragon",
                           "red troll",
                           "red tulip",
                           "rift_secretary",
                           "robber",
                           "robin",
                           "robiny",
                           "rodent",
                           "roe",
                           "rogue",
                           "root",
                           "rotweiler",
                           "rotworm",
                           "rude knight",
                           "rude pirate",
                           "sailor",
                           "saint unicorn",
                           "salesman",
                           "saleswitch",
                           "samurai",
                           "sand troll",
                           "sardine",
                           "scarecrow",
                           "scarwood goblin",
                           "scorpion",
                           "sea elephant",
                           "sea serpent",
                           "seahorse",
                           "seasnake",
                           "seaweed",
                           "secretary",
                           "security guard",
                           "seller",
                           "sergeant",
                           "servant",
                           "sexton",
                           "shadow",
                           "shadowdragon",
                           "shaman",
                           "shark",
                           "sheep",
                           "sheriff",
                           "shopkeeper",
                           "shorse",
                           "shrike",
                           "shy rabbit",
                           "sick witch",
                           "skeleton",
                           "skeleton lich",
                           "skeletonpaladin",
                           "skeletonwarrior",
                           "sleepy rabbit",
                           "slime",
                           "small fish",
                           "small mole",
                           "small sardine",
                           "small thief",
                           "smith",
                           "snake",
                           "snow rabbit",
                           "snowfox",
                           "solamnia npc",
                           "solar",
                           "soldier",
                           "soldier of yendor",
                           "some guard",
                           "sorcerer",
                           "sparrow",
                           "spectre",
                           "spider",
                           "spirit",
                           "spy",
                           "squirrel",
                           "stepmother",
                           "stick",
                           "stone troll",
                           "storyteller",
                           "strong golem",
                           "sturgeon",
                           "surgeon",
                           "svyelunite priest",
                           "swamp thing",
                           "swamp worm",
                           "swamptroll",
                           "swordkeeper",
                           "swordmaster",
                           "talking skeleton",
                           "tarantula",
                           "tattoobear",
                           "teacher",
                           "teddy",
                           "teddybear",
                           "tentacle",
                           "thief",
                           "thief apprentice",
                           "thief chief",
                           "thief guard",
                           "thief journeyman",
                           "thing on a spring",
                           "thorc",
                           "thrull champion",
                           "thrull wizard",
                           "tiger",
                           "titan",
                           "tomato",
                           "tourist",
                           "tower guard",
                           "tower servant",
                           "tramper",
                           "treasure guard",
                           "traveller",
                           "troll",
                           "troll leader",
                           "trumpeter",
                           "trunk",
                           "tuba-player",
                           "turkey",
                           "turtle",
                           "twilight figure",
                           "ugly knight",
                           "ugly pirate",
                           "undead",
                           "undead dragon",
                           "undead orc",
                           "undead troll",
                           "undefined",
                           "urchin",
                           "uruk-hai",
                           "vampire",
                           "vermin exterminator",
                           "very big crocodile",
                           "very big mole",
                           "very drunk pirate",
                           "very drunk pirate indeed",
                           "very large tentacle",
                           "very tired knight",
                           "very ugly pirate",
                           "vesuvian doppelganger",
                           "victim",
                           "vodalian knight",
                           "vodalian mage",
                           "vodalian soldier",
                           "vulture",
                           "vumpire",
                           "wanderer",
                           "warrior",
                           "wasp",
                           "watchdog",
                           "watcher",
                           "watchman",
                           "water-lilly",
                           "water elemental",
                           "watersnake",
                           "weasel",
                           "weed",
                           "welsh castle ghost",
                           "white tulip",
                           "widow",
                           "wildflower",
                           "wildteddy",
                           "will-o'-the-wisp",
                           "will-o-the-wisp",
                           "windrose",
                           "wise man",
                           "wisp",
                           "witch",
                           "witness",
                           "wizard",
                           "wizard of yendor",
                           "wolf",
                           "woman",
                           "woodelf",
                           "woodworm",
                           "worm",
                           "wraith",
                           "wren",
                           "wyrm",
                           "wyvern",
                           "yaro_knight",
                           "yeti",
                           "zombie" ]);
  if ((h=lower_case(name))[0..1] == "a " ||
      h[0..2] == "an " ||
      h[0..3] == "the ")  // starts with an article?
    return 0;  // then it is no natural name.
  return !member(not_natural_names,h);
}
