/* shit blud n cum on myhands */

mapping a, b, c, d, e, f, g, h;

void
reset(status arg)
{
    if(arg) return;
    a = b = c = d = e = f = g = h = ([ ]);
    a = ([
  "acid" : "synthemesc",
  "advice" : "soviet",
  "advised" : "sovietted",
  "alone" : "on my oddy knocky",
  "ancient" : "starry",
  "apologies" : "appy polly loggies",
  "apology" : "appy polly loggy",
  "appearance" : "smot",
  "appeared" : "smotted",
  "appears" : "smots",
  "arm" : "rock",
  "arrogant" : "nadmenny",
  "ass" : "sharries" ]);

   call_out("evB", 1);
}

void
evB()
{
  b = ([
  "babe" : "ptitsa",
  "bad" : "baddiwad",
  "baddest" : "baddiwadest",
  "bag" : "soomka",
  "nuts" : "yarbles",
  "balls" : "yarbles",
  "band" : "banda",
  "barrier" : "shest",
  "bastard" : "bratchny",
  "bathroom" : "vaysay",
  "battle" : "bivta",
  "beak" : "clop",
  "beer" : "firegold",
  "beers" : "firegolds",
  "begin" : "nachinat",
  "beginning" : "nachinatovat",
  "bell" : "collocoll",
  "bellpull" : "zvonock",
  "belly" : "brooko",
  "big" : "bolshy",
  "biggest" : "bolshiest",
  "bishop" : "godman",
  "bit" : "lomtick",
  "bitch" : "soomka",
  "bitches" : "soomkas",
  "blade" : "nozh",
  "blood" : "krovvy",
  "bloody" : "krovvier",
  "bodies" : "plotts",
  "body" : "plott",
  "boner" : "pan-handle",
  "boobs" : "groodies",
  "booze" : "firegold",
  "bought" : "kupetted",
  "boundary" : "shest",
  "boy" : "malchick",
  "brain" : "mozg",
  "brains" : "mozggies",
  "brainy" : "oomny",
  "bread" : "kleb",
  "break" : "cluve",
  "breast" : "groody",
  "briefs" : "neezhnies",
  "broke" : "cluved",
  "brother" : "bratty",
  "brothers" : "bratties",
  "buddies" : "droogs",
  "buddy" : "droog",
  "bum" : "sharries",
  "butt" : "sharries",
  "butter" : "maslo",
  "buttered" : "masloed",
  "buttocks" : "sharries",
  "button" : "knopka",
  "buttoning" : "knopkavat",
  "buy" : "kupet",
  "buying" : "kupetting",
  "cannon" : "pooshka",
  "cash" : "deng",
  "cat" : "koshka",
  "catch" : "lovet",
  "cats" : "koshkas",
  "cattle" : "scoteenavak",
  "catty" : "koshky",
  "caught" : "loveted",
  "cd" : " pop-disk",
  "chain" : "oozy",
  "chained" : "oozied",
  "chains" : "oozies",
  "chaplain" : "charles",
  "charitable" : "sammy",
  "chick" : "ptitsa",
  "cigarette" : "cancer",
  "cinema" : "sinny",
  "cinemas" : "sinnies",
  "clever" : "oomny",
  "clothes" : "platties",
  "club" : "shlaga",
  "clubbed" : "shlagnicked",
  "clubs" : "shlagas",
  "cocaine" : "vellocet",
  "conceited" : "nadmenny",
  "concern" : "shilarny",
  "concerned" : "shilarned",
  "concerning" : "shilarnying",
  "cop" : "rozz",
  "cops" : "rozzies",
  "couple" : "dva",
  "cow" : "scoteena",
  ]);
  call_out("evC", 1);
}

void
evC()
{
  c = ([
  "cows" : "scoteenavak",
  "crap" : "cal",
  "crazy" : "bezoomny",
  "cried" : "horned",
  "criminal" : "prestoopnik",
  "crone" : "lighter",
  "cry" : "platch",
  "crying" : "horning",
  "cup" : "chasha",
  "cupped" : "chashassed",
  "cupping" : "chashassing",
  "cups" : "chashas",
  "cut" : "shive",
  "dad" : "pee",
  "daddy" : "pee",
  "dagger" : "britva",
  "damage" : "vred",
  "damaged" : "vredded",
  "damages" : "vreddies",
  "damaging" : "vreddying",
  "die" : "snuff it",
  "died" : "snuffed it",
  "dig" : "kopat",
  "dirtiest" : "grahznied",
  "dirty" : "grahzny",
  "dollar" : "golly",
  "dollars" : "gollies",
  "doorbell" : "zvonock",
  "drank" : "peeted",
  "dream" : "sneety",
  "dreamed" : "sneeted",
  "dreaming" : "sneeting",
  "dreams" : "sneets",
  "dreamt" : "sneeted",
  "drink" : "peet",
  "drinking" : "peeting",
  "drive" : "yeckate",
  "driving" : "yeckating",
  "drove" : "yeckated",
  "drunk" : "pyahnitsa",
  "dumb" : "gloopy",
  "dumbest" : "gloopiest",
  "ear" : "ooko",
  "ears" : "ookoes",
  "egg" : "eggiweg",
  "erection" : "pan-handle",
  "excellent" : "horrorshow",
  "eye" : "glazz",
  "eyed" : "glazzied",
  "eyeglasses" : "otchkies",
  "eyes" : "glazzies",
  "face" : "litso",
  "faced" : "litsoed",
  "fancied" : "messeled",
  "fanciest" : "messeliest",
  "fancy" : "messel",
  "fantasy" : "sneet",
  "fast" : "skorry",
  "father" : "pee",
  "feet" : "nogas",
  "fellow" : "chelloveck",
  "fight" : "drat",
  "fighting" : "dratsing",
  "filthiest" : "merzkiest",
  "filthy" : "merzky",
  "fist" : "rooker",
  "fists" : "rookers",
  "flat" : "domy",
  "food" : "pishcha",
  "fool" : "nazz",
  "fooled" : "fillied",
  "fooled" : "nazzed",
  "fools" : "nazzes",
  "foot" : "noga",
  "fornicate" : "sod",
  "fornicating" : "sodding",
  "fragrance" : "von",
  "friend" : "droog",
  "friends" : "droogs",
  "friendly" : "droogy",
  "fright" : "poog",
  ]);
  call_out("evD", 1);
}

void
evD()
{
  d = ([
  "frighten" : "poogy",
  "frightened" : "poogly",
  "frightening" : "poogying",
  "fuck" : "sod",
  "fucks" : "sods",
  "fucking" : "sodding",
  "game" : "eegra",
  "gang" : "shaika",
  "garbage" : "cal",
  "geezer" : "ded",
  "gender" : "pol",
  "generous" : "sammy",
  "ghost" : "dook",
  "ghosts" : "dook",
  "girl" : "devotchka",
  "girlfriend" : "sharp",
  "girls" : "devotchkas",
  "glasses" : "otchkies",
  "go" : "itty",
  "god" : "bog",
  "goes" : "itties",
  "going" : "ittying",
  "good" : "dobby",
  "grab" : "skvat",
  "grabbed" : "skvatted",
  "grabbing" : "skvatty",
  "grannies" : "baboochkas",
  "granny" : "baboochka",
  "great" : "bolshy",
  "greater" : "bolshier",
  "greatest" : "bolshiest",
  "groove" : "kopat",
  "group" : "gruppa",
  "groups" : "gruppas",
  "guard" : "chasso",
  "guarded" : "chassoed",
  "guarding" : "chassoing",
  "guffaw" : "guff",
  "guffawed" : "guffed",
  "gun" : "pooshka",
  "gut" : "guttiwut",
  "guts" : "guttiwuts",
  "guy" : "veck",
  "guys" : "vecks",
  "hag" : "baboochka",
  "hair" : "luscious glory",
  "hairdo" : "voloss",
  "hand" : "rook",
  "handed" : "rookered",
  "handkerchief" : "tashtook",
  "hands" : "rooks",
  "happen" : "sloochat",
  "happening" : "sloochavvy",
  "hat" : "shlapa",
  "hats" : "shlapas",
  "head" : "gulliver",
  "heads" : "gullivershear slooshy",
  "heard" : "slooshied",
  "hearing" : "slooshying",
  "heaven" : "bog and all his angels",
  "helmet" : "shlem",
  "helmets" : "shlems",
  "hit" : "tolchock",
  "hitting" : "tolchocking",
  "hole" : "yahma",
  "holes" : "yahmas",
  "horrible" : "stracky",
  "horror" : "strack",
  "house" : "domy",
  "hurt" : "vred",
  "hurting" : "vreddying",
  "injure" : "cluve",
  "injured" : "cluved",
  "insane" : "bezoomny",
  "interest" : "interessovat",
  "interesting" : "interessovatting",
  "intestines" : "keeshkas",
  "intoxicated" : "pyahnitsa",
  "jail" : "staja",
  "jailed" : "plennied",
  "jam" : "jammiwam",
  "jew" : "yahoody",
  ]);
  call_out("evE", 1);
}

void
evE()
{
  e = ([
  "jewish" : "yahood",
  "jews" : "yahoodies",
  "joy" : "radosty",
  "key" : "klootch",
  "keys" : "klootches",
  "kill" : "oobivat",
  "killed" : "oobivatted",
  "killing" : "oobivatting",
  "kills" : "oobivatties",
  "kiss" : "lubbilub",
  "kisses" : "lubbilubs",
  "kissing" : "lubbilubbing",
  "knickers" : "neezhnies",
  "knife" : "nozh",
  "knives" : "nozhies",
  "knock" : "clop",
  "knocked" : "clopped",
  "ladies" : "damas",
  "lady" : "dama",
  "laugh" : "smeck",
  "laughed" : "smecked",
  "laughing" : "smecking",
  "laughs" : "smecks",
  "lead" : "privodeet",
  "leader" : "privodevat",
  "leave" : "ookadeet",
  "leaves" : "ookadeeties",
  "left" : "ookadetted",
  "leg" : "noga",
  "libraries" : "biblios",
  "library" : "biblio",
  "life" : "jeezny",
  "lip" : "goober",
  "lips" : "goobers",
  "lipstick" : "goober-muck",
  "liquor" : "firegold",
  "listen" : "sloosh",
  "listened" : "slooshed",
  "listening" : "slooshying",
  "listens" : "slooshes",
  "little" : "malenky",
  "lives" : "jeeznies",
  "lonesome" : "oddy knocky",
  "look" : "smot",
  "looked" : "smottied",
  "looking" : "smottovat",
  "looks" : "viddies",
  "loot" : "cutter",
  "loud" : "gromky",
  "louder" : "gromkier",
  "loudest" : "gromkiest",
  "lsd" : "synthemsec",
  "mad" : "bezoomny",
  "maim" : "cluve",
  "maimed" : "cluve",
  "mama" : "em",
  "man" : "moodge",
  "mate" : "chelloveck",
  "men" : "moodges",
  "microwave" : "nuke-a-tron",
  "milk" : "moloko",
  "milking" : "molokoing",
  "mind" : "rassoodock",
  "minds" : "rassoodocks",
  "minister" : "charlie",
  "minute" : "minoota",
  "minutes" : "minootas",
  "mom" : "em",
  "mommy" : "em",
  "money" : "pretty polly",
  "morsel" : "lomtick",
  "mother" : "em",
  "mouth" : "rot",
  "mouthing" : "rotting",
  "movie" : "sinny",
  "movies" : "sinny",
  "mull" : "drencrom",
  "mum" : "em",
  "mumble" : "chumble",
  "mumbled" : "wonked",
  "munificent" : "sammy",
  "naked" : "nagoy",
  "name" : "eemya",
  "named" : "eemyaed",
  "nap" : "zasnoot",
  "neck" : "shiyah",
  "necks" : "shiyahs",
  "nerdy" : "dobby",
  "newspaper" : "gazetta",
  "newspapers" : "gazettas",
  "night" : "nochy",
  "noise" : "shoom",
  "noisiest" : "shoomiest",
  "noisy" : "shoomy",
  "nonsense" : "chepooka",
  "nose" : "morder",
  "odor" : "von",
  "odour" : "von",
  "office" : "cantora",
  "offices" : "cantoras",
  ]);

  call_out("evF", 1);
}

void
evF()
{
  f = ([
  "one" : "odin",
  "organisation" : "vareetovat",
  "organise" : "vareet",
  "organising" : "vareeting",
  "organization" : "vareetovat",
  "organize" : "vareet",
  "organizing" : "vareeting",
  "organs" : "keeshkas",
  "pair" : "dva",
  "panties" : "neezhnies",
  "parents" : "pee and em",
  "paw" : "lapa",
  "paws" : "lapas",
  "peanuts" : "hen-korm",
  "people" : "chellovecks",
  "people" : "lewdies",
  "peopled" : "lewdied",
  "perfume" : "von",
  "person" : "chelloveck",
  "phantom" : "dook",
  "piece" : "lomtick",
  "pieced" : "lomticked",
  "pieces" : "lomticks",
  "piecing" : "lomticking",
  "pillow" : "podooshka",
  "place" : "mesto",
  "places" : "mestoes",
  "plan" : "vareet",
  "planned" : "vareeted",
  "planning" : "vareeting",
  "play" : "filly",
  "played" : "fillied",
  "playing" : "fillying",
  "pocket" : "carman",
  "pockets" : "carmans",
  "policeman" : "millicent",
  "policemen" : "millicents",
  "portion" : "lomtick",
  "potato" : "kartoffel",
  "potatoes" : "kartoffels",
  "preacher" : "charlie",
  "priest" : "charles",
  "prisoner" : "plenny",
  "prisoners" : "plennies",
  "produce" : "prod",
  "produced" : "prodded",
  "producer" : "prodovat",
  "produces" : "prods",
  "producing" : "prodding",
  "punch" : "fist",
  "punched" : "fisted",
  "punching" : "fisting",
  "purchase" : "kupet",
  "push" : "tolchock",
  "quick" : "skorry",
  "quickly" : "skorry",
  "razor" : "britva",
  "remarkable" : "zammechat",
  "residence" : "domy",
  "rest" : "zasnoot",
  "resting" : "zasnooting",
  "rich" : "bugatty",
  "rip" : "razrez",
  "ripped" : "razrezzed",
  "ripping" : "razrezzing",
  "rob" : "crast",
  "robbed" : "crasted",
  "robbing" : "crasting",
  "said" : "skazzed",
  "sang" : "warbled",
  "sarcastic" : "sarky",
  "saying" : "skazating",
  "say" : "skazat",
  "scare" : "poogy",
  "scared" : "poogly",
  "scary" : "poogying",
  "scheme" : "vareet",
  "school" : "skolliwoll",
  "schools" : "skolliwolls",
  "scratch" : "skirk",
  "scratched" : "skirked",
  "scratching" : "skirking",
  "scream" : "creech",
  "screamed" : "creeched",
  "screaming" : "creeching",
  "screams" : "creeches",
  "screw" : "sod",
  "screwing" : "sodding",
  "see" : "viddy",
  "seeing" : "viddying",
  "sees" : "viddies",
  "sex" : "the old in-out in-out",
  "shiny" : "silver-like",
  "shit" : "cal",
  "shoe" : "sabog",
  "shoes" : "sabogs",
  "shoulder" : "pletcho",
  "shoulders" : "pletchoes",
  "shriek" : "creech",
  "shrieked" : "creeched",
  "sick" : "bolnoy",
  ]);
  call_out("evG", 1);
}

void
evG()
{
  g = ([
  "sickest" : "bolnoyest",
  "sing" : "warble",
  "singing" : "warbling",
  "skeleton-key" : "polyclef",
  "slash" : "razrez",
  "slashed" : "razrezzed",
  "slashing" : "razrezzing",
  "sleep" : "spatchka",
  "sleeping" : "spatting",
  "sleeps" : "spats",
  "sleepy" : "fagged",
  "slept" : "spatted",
  "slice" : "shive",
  "sliced" : "shivvied",
  "slicing" : "shiving",
  "slipper" : "toofle",
  "slippers" : "toofles",
  "small" : "malenky",
  "smart" : "oomny",
  "smell" : "von",
  "smelled" : "vonnied",
  "smelling" : "nuking",
  "smelly" : "vonny",
  "smelt" : "nuked",
  "snack" : "mounch",
  "snacks" : "mounches",
  "snout" : "morder",
  "snuff" : "snoutie",
  "sob" : "blub",
  "sobbed" : "blubbed",
  "sobbing" : "blubbing",
  "soiled" : "grazzy",
  "song" : "warble",
  "songs" : "warbles",
  "sound" : "zvook",
  "sounds" : "zvooks",
   "says" : "govoreets",
  "speak" : "govoreet",
  "speaks" : "govoreets",
  "speaking" : "govoreeting",
  "specs" : "otchkies",
  "spectacles" : "otchkies",
  "splash" : "plesk",
  "splashed" : "ploshed",
  "splashing" : "ploshing",
  "spoke" : "govoreeted",
  "spray" : "plesk",
  "sprayed" : "plesked",
  "spraying" : "plesking",
  "start" : "nachinat",
  "steaks" : "steakiwakes",
  "steal" : "crast",
  "stealing" : "crasting",
  "stiffie" : "pan-handle",
  "stink" : "von",
  "stinking" : "vonny",
  "stinky" : "vonny",
  "stole" : "crasted",
  "story" : "raskazz",
  "studious" : "dobby",
  "stupid" : "gloopy",
  "stupidest" : "gloopiest",
  "sugar" : "sakar",
  "sugared" : "sakary",
  "sweet" : "sladky",
  "sweetest" : "sladkvat",
  "take" : "shvat",
  "taking" : "shvatty",
  "talk" : "govoreet",
  "talked" : "govoreeted",
  "talking" : "govoreeting",
  "tea" : "chai",
  "teen" : "nadsat",
  "teenager" : "nadsat",
  "teenagers" : "nadsats",
  "teeth" : "zoobies",
  "terrible" : "oozhassny",
  "terrified" : "spoogly",
  "terrifying" : "spoogy",
  "terror" : "spoog",
  "testes" : "yarbles",
  "testicle" : "yarble",
  "testicles" : "yarbles",
  "thing" : "veshch",
  "things" : "veshches",
  "thought" : "messel",
  "thoughts" : "messels",
  "three" : "tree",
  "threw" : "brosayed",
  "throat" : "gorlo",
  "throats" : "gorloes",
  "throw" : "brosay",
  "throwing" : "brosaying",
  "time" : "raz",
  "timed" : "razzied",
  "timing" : "razovat",
  "tired" : "fagged",
  "tiring" : "faggy",
  "tit" : "groody",
  "tits" : "groodies",
  "tobacco" : "snoutie",
  "toilet" : "vaysay",
  "tomcat" : "kot",
  "tongue" : "yahzick",
  "tongues" : "yahzicks",
  "tonight" : "this nochy",
  "took" : "shvatted",
  "tooth" : "zooby",
  "trace" : "dook",
  "trout" : "forella",
  "twit" : "shoot",
  "two" : "dva",
  "underpants" : "neezhnies",
  "understand" : "pony",
  "understanding" : "ponying",
  "understood" : "ponied",
  "underwear" : "neezhnies",
  "upset" : "razdraz",
  "upsetting" : "razdrazled",
  "useful" : "polezny",
  "valuable" : "dorogoy",
  "violence" : "ultra-violence",
  ]);
  call_out("evH", 1);
}

void
evH()
{
  h = ([
  "virtuous" : "dobby",
  "voice" : "goloss",
  "voices" : "golosses",
  "wailing" : "blubbing",
  "waist" : "tally",
  "walk" : "gooly",
  "walked" : "goolied",
  "walking" : "goolying",
  "wall" : "shest",
  "walled" : "shested",
  "walls" : "shests",
  "wash" : "cheest",
  "washed" : "cheested",
  "washing" : "cheesting",
  "washroom" : "vaysay",
  "wealthy" : "bugatty",
  "weep" : "platch",
  "weeping" : "platching",
  "well" : "horrorshow",
  "wept" : "platched",
  "wife" : "zheena",
  "wild" : "flip",
  "window" : "okno",
  "windows" : "oknoes",
  "wipe" : "osoosh",
  "wiped" : "osooshied",
  "wiping" : "osooshing",
  "with" : "with like",
  "wives" : "zheenas",
  "woman" : "cheena",
  "women" : "cheenas",
  "wonderful" : "choodessny",
  "word" : "slovo",
  "words" : "slovoes",
  "work" : "rabbit",
  "worked" : "rabbited",
  "working" : "rabbiting",
  "works" : "rabbits",
  "worst" : "baddiwadest",
  "yell" : "horn",
  "young" : "molodoy",
  "youth" : "nadsat",
]);

}

string
bacala(string heh)
{
    string oi;

    if(oi = a[heh]) return oi;
    else if(oi = b[heh]) return oi;
    else if(oi = c[heh]) return oi;
    else if(oi = d[heh]) return oi;
    else if(oi = e[heh]) return oi;
    else if(oi = f[heh]) return oi;
    else if(oi = g[heh]) return oi;
    else if(oi = h[heh]) return oi;
}

string
nadsat_it(string heh)
{
    object x, d;
    string *w, p, q, bog, goodbar;
    int s, l;

    if(((l = (strlen(heh) - 1)) > -1) && 
      ((goodbar = heh[l..l]) == "." ||
        goodbar == "?" || goodbar == "!"))
    { 
      p = goodbar; heh = heh[0..l - 1]; 
    }
    s = sizeof(w = explode(heh, " "));
    while(s --)
      if(bog = bacala(w[s]))
      {
        if((l = strlen(bog) - 1) > -1 &&
            (goodbar = bog[l..l]) && (goodbar == "." || goodbar == "?" ||
            goodbar == "!"))
        {        
           bog = bog[0..l-1]; 
           q = goodbar;
        }
        w[s] = bog + (q ? q : "");
    }

    heh = implode(w, " ") + (p ? p : "");
    if((x = this_player()) && (d = present("drunk", x)) &&
      creator(d) == "sado")
        heh = (string)d->distort(heh);
    return heh;
}
