#!/bin/sh
ls -F players > PLLS
grep / PLLS |\
awk -F/ '
{ jump = $1; printf("tar -cf %s.tar %s\n", jump, jump); 
  printf ("gzip %s.tar\n", jump);
 printf ("rm -r %s\n", jump);
  printf("mv %s.tar.gz %s.tgz\n",jump,jump);
}' > players/WIZ_BAK 
rm PLLS
chmod 700 players/WIZ_BAK
ls -F > RTLS
grep / RTLS |\
awk -F/ '
{ jump = $1; printf("tar -cf %s.tar %s\n", jump, jump); 
  printf ("gzip %s.tar\n", jump);
  printf ("rm -r %s\n", jump);
  printf("mv %s.tar.gz %s.tgz\n",jump,jump);
}' > ROOT_BAK 
rm RTLS
chmod 700 ROOT_BAK

