#!/bin/sh
ls -F players > PLLS
grep / PLLS |\
awk -F/ '
{ jump = $1; printf("tar -cf /home/petebre/backup/players/%s.tar %s\n",
jump, jump); 
  printf ("gzip /home/petebre/backup/players/%s.tar\n", jump);
}' > players/WIZ_BAK 
rm PLLS
chmod 700 players/WIZ_BAK
ls -F > RTLS
grep / RTLS |\
awk -F/ '
{ jump = $1; printf("tar -cf /home/petebre/backup/%s.tar %s\n", jump,
jump); 
  printf ("gzip /home/petebre/backup/%s.tar\n", jump);
}' > ROOT_BAK 
rm RTLS
chmod 700 ROOT_BAK

