#! /bin/sh
#
# This program takes a single argument, and removes all player.o files
# of level Argument or less.  Ie. purge 1 would remove all players of 
# less than or equal to level 1.
# This program was written by Tom Link
#
cd pfiles
for i in */*.o
do
    if [ `awk '$1 == "experience" { print $2}' $i` -le $1 ]
    then
        echo -n Purging $i:
        grep experience $i
    fi
done
