#!/bin/sh
cd players
egrep '^level |^cap_name |^age ' *.o |\
sed -e 's/\.o:/ /' -e 's/\"//g' |\
sort |\
awk '
$2=="cap_name" { jump = $1; }
$2=="age" { age = $3; }
$2=="level" { if ($3 > 19) printf("tar -cf /user2/nirvana/bakup/%s.tar %s\n", jump, jump);
	    age = 0; jump = "XX"; }' |\
sort +rn1 +rn2 |\
head -100
