inherit "obj/monster";
reset(arg){
   object gold,amulet,berzerker;
   ::reset(arg);
   if(arg) return;
   set_name("hiss");
   set_race("dragon");
   set_alias("dragon");
   set_short("Hiss, black dragon of acid");
   set_long("Hiss, a giant green dragon, leads the invasion force!\n");
   set_level(23);
   set_hp(1);
   set_al(-1000);
   set_wc(22);
   set_ac(13);
   set_aggressive(1);
   set_chat_chance (15);
   load_chat("Hiss hisses, 'My master, Zacor will destroy you!'\n");
   load_chat("Hiss snarls, 'We will destroy the vale!'\n");
   load_chat("'Your efforts are too little, too late,' snarls Hiss.\n");
   load_chat("Hiss cries, 'You pathetic food things. Die!'\n");
   set_chance(15);
   set_spell_dam(random(20)+10);
   set_spell_mess1("Hiss inhales deeply and breathes acid!\n");
   set_spell_mess2("Your skin melts at the touch of Hiss's wicked acid!\n");
   gold=clone_object("obj/money");
   gold->set_money(60000);
   move_object(gold,this_object());
   amulet=clone_object("players/ladyfinger/armor/gold_amulet");
   move_object(amulet,this_object());
   berzerker=clone_object("players/ladyfinger/weapon/berzerker");
   move_object(berzerker,this_object());
}
