#ifndef _banking_shopinterface_h
#define _banking_shopinterface_h

#define SHOPKEEPER_LEAVE_REASON_TAKE_STOCK     1
#define SHOPKEEPER_LEAVE_REASON_LOOK_FOR_WARES 2
#define SHOPKEEPER_LEAVE_REASON_WRITE_LIST     3
#define SHOPKEEPER_LEAVE_REASON_MAKE_LIST      4
#define SHOPKEEPER_LEAVE_REASON_COLLECT_WARES  5
#define SHOPKEEPER_LEAVE_REASON_MAKE_ROOM      6

#define SHOPKEEPER_ARRIVE_INFO_WITH_PRICELIST  1
#define SHOPKEEPER_ARRIVE_INFO_AFTER_LOOKING   2
#define SHOPKEEPER_ARRIVE_INFO_WITH_LIST       3
#define SHOPKEEPER_ARRIVE_INFO_WITH_WARES      4
#define SHOPKEEPER_ARRIVE_INFO_TO_STORE        5

#endif
