#define MY_GUILD        this_player()->query_guild()
#define MY_CLASS        this_object()->query_guild_class()
#define GUILD           "cleric"
#define Me              this_player()
#define Name            this_player()->query_name()
#define NAME            this_player()->query_real_name()
#define Level           this_player()->query_level()
#define Pro             this_player()->query_pronoun()
#define Pos             this_player()->query_possessive()
#define Obj             this_player()->query_objective()
#define SP              this_player()->query_sp()
#define Ssp(xx)         this_player()->add_spell_point(-xx)
#define Wis             this_player()->query_attrib("pie")
#define Align           this_player()->query_alignment()
#define PK              this_player()->query_IAMAPLAYERKILLER()
#define Glevel          this_object()->query_guild_level()
#define Gexp            this_object()->query_guild_exp()
#define Gain(xx)        this_object()->add_guild_exp(xx)
#define Mana            this_object()->query_mana()
#define MANA            this_object()->query_max_mana()
#define Drain(xx)       this_object()->add_mana(-xx)
#define Boost(xx)       this_object()->add_mana(xx)
#define Faith           this_object()->query_faith()
#define Afaith          this_object()->add_faith(xx)
#define Sfaith(xx)      this_object()->add_faith(-xx)
#define Donated         this_object()->query_donated()
#define Donate(xx)      this_object()->add_donate(xx)
#define Gtitle          this_object()->query_guild_title()
#define Needed          this_object()->query_exp_needed()
#define Badge           this_object()
#define HEAL(xx)        heal_self(xx)
#define Env(xx)         environment(xx)
#define True            1
#define False           0
#define EXP10           (Glevel * 2) + (Faith * 10)
#define EXP10A          (Glevel * 2) + (Faith * 10) + (random(10))
#define EXP20           (Glevel * 5) + (Faith * 10)
#define EXP20A          (Glevel * 5) + (Faith * 10) + (random(20))
#define EXP30           (Glevel * 10) + (Faith * 10)
#define EXP30A          (Glevel * 10) + (Faith * 10) + (random(30))
#define EXP40           (Glevel * 20) + (Faith * 10)
#define EXP40A          (Glevel * 20) + (Faith * 10) + (random(40))
#define EXP50           (Glevel * 25) + (Faith * 10)
#define EXP50A          (Glevel * 30) + (Faith * 10) + (random(50))

#define START_WRAP_LENGTH 5
#define DEFAULT_INDENT  4
#define WRAP_LENGTH  75

