#define TP  this_player()
#define TN  TP->query_name()
#define RN  TP->query_real_name()
#define ORN ob->query_real_name()
#define CAP capitalize
#define TPN CAP(TN)
#define OPN CAP(ob->query_name())
#define GEN TP->query_possessive()
#define ATTACK environment(this_object())->query_attack()
#define ENV environment
#define EO  environment(ob)
#define ET  environment(TP)
#define FP  find_player
#define TE  tell_object
#define TR  tell_room
#define WHO CAP(who)
#define STR CAP(str)
#define PRE present
#define MEAT TP->query_attack()
#define log "/players/snow/closed/cyber/log/"
#define TOOL "/players/snow/closed/cyber/newdaem.c"
#define ETO environment(this_object())
#define SAVE "players/snow/closed/cyber/ninjas/"
#define EMP1 "dune"
#define EMP2 "snow"
