/* Guild daemon for the Necromancers   -Dar */
#include "../defs.h"

#include "/players/wocket/necro/power/necro_who.h"
#include "/players/wocket/necro/power/necro_gwho.h"
#include "/players/wocket/necro/power/necro_score.h"
#include "/players/wocket/necro/power/autopsy.h"
#include "/players/wocket/necro/power/preserve.h"
#include "/players/wocket/necro/power/touch_chill.h"
#include "/players/wocket/necro/power/touch_spect.h"
#include "/players/wocket/necro/power/dembrace.h"
#include "/players/wocket/necro/power/wraithform.h"
#include "/players/wocket/necro/power/summon_tool.h"
#include "/players/wocket/necro/power/ddoor.h"
#include "/players/wocket/necro/power/assasination.h"
#include "/players/wocket/necro/power/dis_burial.h"
#include "/players/wocket/necro/power/consume.h"
#include "/players/wocket/necro/power/badmoon.h"
#include "/players/wocket/necro/power/drain_life.h"
#include "/players/wocket/necro/power/buried_alive.h"
#include "/players/wocket/necro/power/con_grave.h"
#include "/players/wocket/necro/power/raise_portal.h"
#include "/players/wocket/necro/power/aban_hope.h"
#include "/players/wocket/necro/power/sphere.h"
#include "/players/wocket/necro/power/conf_cloak.h"
#include "/players/wocket/necro/power/syphon.h"
#include "/players/wocket/necro/power/grafting.h"
#include "/players/wocket/necro/power/ghast_stench.h"
#include "/players/wocket/necro/power/deathfog.h"
#include "/players/wocket/necro/power/raise_dead.h"
#include "/players/wocket/necro/power/caress.h"
#include "/players/wocket/necro/power/sad_glee.h"
#include "/players/wocket/necro/power/banshee.h"
#include "/players/wocket/necro/power/blind_agony.h"

