/* Guild daemon for the Necromancers   -Dar */
#include "defs.h"

#include "/players/daranath/guild/power/necro_who.h"
#include "/players/daranath/guild/power/necro_gwho.h"
#include "/players/daranath/guild/power/necro_score.h"
#include "/players/daranath/guild/power/autopsy.h"
#include "/players/daranath/guild/power/preserve.h"
#include "/players/daranath/guild/power/touch_chill.h"
#include "/players/daranath/guild/power/touch_spect.h"
#include "/players/daranath/guild/power/dembrace.h"
#include "/players/daranath/guild/power/wraithform.h"
#include "/players/daranath/guild/power/summon_tool.h"
#include "/players/daranath/guild/power/ddoor.h"
#include "/players/daranath/guild/power/assasination.h"
#include "/players/daranath/guild/power/dis_burial.h"
#include "/players/daranath/guild/power/consume.h"
#include "/players/daranath/guild/power/badmoon.h"
#include "/players/daranath/guild/power/drain_life.h"
#include "/players/daranath/guild/power/buried_alive.h"
#include "/players/daranath/guild/power/con_grave.h"
#include "/players/daranath/guild/power/raise_portal.h"
#include "/players/daranath/guild/power/aban_hope.h"
#include "/players/daranath/guild/power/sphere.h"
#include "/players/daranath/guild/power/conf_cloak.h"
#include "/players/daranath/guild/power/syphon.h"
#include "/players/daranath/guild/power/grafting.h"
#include "/players/daranath/guild/power/ghast_stench.h"
#include "/players/daranath/guild/power/deathfog.h"
#include "/players/daranath/guild/power/raise_dead.h"
#include "/players/daranath/guild/power/caress.h"
#include "/players/daranath/guild/power/sad_glee.h"
#include "/players/daranath/guild/power/banshee.h"
#include "/players/daranath/guild/power/blind_agony.h"

