string FANNAME;
int number;
number = random(31);
switch(number) {
      case 0: FANNAME = "joe"; break;
      case 1: FANNAME = "jeff"; break;
      case 2: FANNAME = "ray"; break;
      case 3: FANNAME = "mike"; break;
      case 4: FANNAME = "tom"; break;
      case 5: FANNAME = "al"; break;
      case 6: FANNAME = "steve"; break;
      case 7: FANNAME = "tim"; break;
      case 8: FANNAME = "alan"; break;
      case 9: FANNAME = "bill"; break;
      case 10: FANNAME = "jaremy"; break;
      case 11: FANNAME = "dick"; break;
      case 12: FANNAME = "chris"; break;
      case 13: FANNAME = "john"; break;
      case 14: FANNAME = "dave"; break;
      case 15: FANNAME = "ed"; break;
      case 16: FANNAME = "joe"; break;
      case 17: FANNAME = "ken"; break;
      case 18: FANNAME = "greg"; break;
      case 19: FANNAME = "lonnie"; break;
      case 20: FANNAME = "pete"; break;
      case 21: FANNAME = "pat"; break;
      case 22: FANNAME = "mark"; break;
      case 23: FANNAME = "scott"; break;
      case 24: FANNAME = "dave"; break;
      case 25: FANNAME = "skeeter"; break;
      case 26: FANNAME = "darren"; break;
      case 27: FANNAME = "keith"; break;
      case 28: FANNAME = "sean"; break;
      case 29: FANNAME = "doug"; break;
      case 30: FANNAME = "erik"; break;}
