/*****************************************************************************
 *      File:                   bunnyDM.c
 *      Function:               Common functions for bunnies
 *      Author(s):              Mizan@Nirvana
 *      Copyright:              Copyright (c) 2011 Mizan@Nirvana
 *                              All Rights Reserved.
 *      Source:                 2/2011
 *      Notes:                 
 *      Change History:         
 ****************************************************************************/
#include "../definitions.h"
string *my_names;
string *my_emotes;

get() {
    return 0;
}
short() {
    return "A server named (bunny)";
}
id(str) {
    return str == "bunny" || str == "server";
}


string get_rabbit_name() {
    return my_names[random(sizeof(my_names))];
}


string get_emote() {
    return my_emotes[random(sizeof(my_emotes))];
}


void reset(int arg)
{
    /* move ourselves home. */
    move_object(this_object(), DAEMON_HOME);

    if (!arg)
    {
	my_emotes = ({
	    "says: Wow. Look at the manboobs on THAT one...",
	    "says: Hop. Hop. Hop.",
	    "says: I'm not really sure if you should do that.",
	    "looks at you.",
	    "peers at you quizically.",
	    "says: That's a funny looking weapon.",
	    "says: I'm looking for some carrots... damnit.",
	    "says: Hey! Have you guys seen the JUICE BAR?!",
	    "sniffles and appears to be trying to sneeze.",
	});

        my_names = ( {

            "Abracadabra",
            "Ace",
            "Akeeta",
            "Alec",
            "Alex",
            "Alfalfa",
            "Alfie",
            "Alley",
            "Amigo",
            "Angel",
            "Angora",
            "Annabelle",
            "Aphrodite",
            "Apollo",
            "April",
            "Aquarius",
            "Archie",
            "Astro",
            "Athena",
            "Auto",
            "Autumn",
            "Babe",
            "Babe Ruth",
            "Baby",
            "Bacardi",
            "Baggins",
            "Bailey",
            "Baloo",
            "Bam",
            "Bam Bam",
            "Bambi",
            "Bambina",
            "Bandit",
            "Barbie",
            "Barney",
            "Bashful",
            "Basil",
            "Batman",
            "Bazzle",
            "Beans",
            "Bell",
            "Bella",
            "Benji",
            "Benny",
            "Bently",
            "Bernadette",
            "Bianca",
            "Big Balls",
            "Big Boy",
            "Big Foot",
            "Bigwig",
            "Billy",
            "Bingo",
            "Binky",
            "Biscotti",
            "Biscuit",
            "Bitch Tits",
            "Black Beard",
            "Black Jack",
            "Blackavar",
            "Blackie",
            "Blaze",
            "Blinky",
            "Blitz",
            "Blizzard",
            "Blu",
            "Bluebell",
            "Bobby B.",
            "BoBo",
            "Bon Bon",
            "Bonsai",
            "Boo Boo",
            "Brambles",
            "Breezy",
            "Briar",
            "Brownie",
            "Bruno",
            "Bubba",
            "Bubblegum",
            "Bubbles",
            "Buckwheat",
            "Bucky",
            "Buddy",
            "Buddy Holly",
            "Buffy",
            "Bugs",
            "Bugs Bunny",
            "Bugster",
            "Bugsy",
            "Buhda",
            "Bullwinkle",
            "Bunnicula",
            "Bunny",
            "Bunny Face",
            "Bunny Foo Foo",
            "Bunnyta",
            "Buster",
            "Butch",
            "Buttercup",
            "Butterscotch",
            "Buttons",
            "Cadburry",
            "Caesar",
            "Camron",
            "Cannoli",
            "Cappuccino",
            "Caramel",
            "Carrot",
            "Casey",
            "Casper",
            "Cecile",
            "Champ",
            "Champion",
            "Chance",
            "Charlie",
            "Charlie Brown",
            "Charligh",
            "Charmin",
            "Chase",
            "Chaz",
            "Checkers",
            "Cheeko",
            "Chesney",
            "Chester",
            "Chesterfield",
            "Chewbacca",
            "Chewy",
            "Chief",
            "Chino",
            "Chipper",
            "Chiquita",
            "Chloe",
            "Chocolate",
            "Chocolate Bar",
            "Chocolate Chip",
            "Chub Chub",
            "Chubby",
            "Chuck",
            "Chunk",
            "Cinna Bun",
            "Cinnamon",
            "Clementine",
            "Cleo",
            "Cleopatra",
            "Clover",
            "Clyde",
            "Cocoa",
            "Coffee",
            "Coffee Bean",
            "Comanche",
            "Cookie",
            "Cookies & Cream",
            "Cooper",
            "copper",
            "Cornelius",
            "Cosmo",
            "Cottontail",
            "Cracker Jack",
            "Crazy Horse",
            "Crazy Rabbit",
            "Critter",
            "Crystal",
            "Cuddles",
            "Cupcake",
            "Cupid",
            "Curious George",
            "Cutiepie",
            "Daffy",
            "Daisy",
            "Dakota",
            "Dallas",
            "Dallie",
            "Dancer",
            "Dandelion",
            "Dandy",
            "Danni",
            "Darth Vader",
            "Dasher",
            "Delilah",
            "Diamond",
            "Diego",
            "Digby",
            "Dillon",
            "Dixie",
            "Dizzy",
            "Dolly",
            "Domino",
            "Doodles",
            "Dopey",
            "Dora",
            "Dorothy",
            "Dr. Bunny",
            "Dude",
            "Dudley",
            "Duke",
            "Dusty Rusty",
            "Dutch",
            "Dutchess",
            "Earnhardt",
            "Ebony",
            "Ed",
            "Einstein",
            "Elfie",
            "Elmer",
            "Elmo",
            "Elvis",
            "Emily",
            "Emmy",
            "Energizer Bunny",
            "Ernie",
            "Eve",
            "Ewok",
            "Fast Eddie",
            "Fast Freddie",
            "Fatty",
            "Fido",
            "Fifi",
            "Figaro",
            "Flakey",
            "Flash",
            "Flip Flop",
            "Flo",
            "Floppy",
            "Floppy Puff Puff",
            "Flopsy",
            "Flossy",
            "Fluffy",
            "Fluffy Cake",
            "Fluffy Girl",
            "Foxy",
            "Frankie",
            "Frapppacinno",
            "Freckles",
            "Fred",
            "Freedom",
            "Freeway",
            "Frisbee",
            "Frisky",
            "Fritz",
            "Frosty",
            "Fu Manchu",
            "Fudge",
            "Fuck Bomb",
            "Fuck Cakes",
            "Fuzzy",
            "Gabby",
            "Garth",
            "Geronimo",
            "Gilligan",
            "Ginger",
            "Giorgio",
            "Gizmo",
            "Goofy",
            "Groucho",
            "Gucci",
            "Guido",
            "Gypsy",
            "Hans",
            "Happy",
            "Harlequin",
            "Harley",
            "Harli",
            "Harry Potter",
            "Harvey",
            "Has en pheffer",
            "Hawk",
            "Haystack",
            "Hazel",
            "Hazelnut",
            "Hefner",
            "Heidi",
            "Henry",
            "Herbie",
            "Hercules",
            "Hershey",
            "Hip Hop",
            "Hippityhoppity Hippity Hoppity",
            "Hippy",
            "Holly",
            "Homer",
            "Honey",
            "Honey Bun",
            "Honey Bunny",
            "Honeydew",
            "Honeysuckle",
            "Hoppity",
            "Hoppy",
            "Hopscotch",
            "Hopup",
            "Hot Dog",
            "Hot Lips",
            "Houdini",
            "Huck",
            "Huggy",
            "Hunny bunny",
            "Hyde",
            "Ice Man",
            "J.J.",
            "Jack Black",
            "Jack Pot",
            "Jack Rabbit",
            "Jackaroo",
            "Jackie Chan",
            "Jade",
            "Jake",
            "James Bond",
            "James Dean",
            "Jasmine",
            "Java",
            "Jax",
            "Jazz",
            "Jazzy",
            "Jedi",
            "Jelly Bean",
            "Jelly Belly",
            "Jessamine",
            "Jessica Rabbit",
            "Jessie",
            "Jester",
            "Jeszy",
            "Jett",
            "Jilly",
            "Jo Jo",
            "Joey",
            "John Wayne",
            "Joker",
            "Jr.",
            "Jynx",
            "Kalulu",
            "Kammanche",
            "Karamel",
            "Kicker",
            "Kiki",
            "King",
            "Kipper",
            "Kirby",
            "Kiss",
            "Kitten",
            "Knight",
            "Kobi",
            "Kokomo",
            "Koo Koo",
            "Kotten",
            "Lacey",
            "Lady",
            "Lady Luck",
            "Lady Pancakes McFluffy",
            "Laredo",
            "Lavender",
            "Leo",
            "Levi",
            "Licorice",
            "Lightning",
            "Lilly",
            "Linus",
            "Little Bunny",
            "Little Fella",
            "Lola",
            "Lucky Jr.",
            "Lucy",
            "Lulu",
            "M&M",
            "Madame",
            "Maggie",
            "Magic",
            "Magnolia",
            "Malibu",
            "Mango",
            "Marilyn Monroe",
            "Marmalade",
            "Marshmallow",
            "Matilda",
            "Maui",
            "Max",
            "Maxi",
            "May Bell",
            "Merlin",
            "Mickey",
            "Midnight",
            "Miffy",
            "Millie",
            "Milly-Mop",
            "Mischief",
            "Miss Futtbucker",
            "Miss Isabelle",
            "Miss Muffit",
            "Miss Pepper",
            "Misty",
            "Mitsy",
            "Mocha",
            "Molly",
            "Mookie",
            "Mops",
            "Mopsy",
            "Mr. Bojangles",
            "Mr. Bunjovi",
            "Mr. Ed",
            "Mr. Fluffles",
            "Mr. Magoo",
            "Mr. Miyagi",
            "Mr. Pibb",
            "Mr. President",
            "Mr. Sparkles",
            "Mr. T",
            "Mr. Velvet Ears",
            "Mr. Wiskers",
            "Ms. Wiggles",
            "Muffin",
            "Mugs",
            "Munchkin",
            "Muppet",
            "Murderface",
            "Mustang",
            "Mystery",
            "Nalla",
            "Nancy Drew",
            "Napoleon",
            "Navigator",
            "Nemo",
            "Nibbler",
            "Nibbles",
            "Nike",
            "Nipsy",
            "Noah",
            "Noel",
            "Nugget",
            "Nutmeg",
            "Oliver",
            "Ollie",
            "Olly",
            "Onyx",
            "Ophelia",
            "Oreo",
            "Oscar",
            "Otto",
            "Oz",
            "Paddy",
            "Pal",
            "Pancake",
            "Pancho",
            "Panda",
            "Pansy",
            "Patches",
            "Peaches",
            "Peanut",
            "Peanut Butter",
            "Pebbles",
            "Peepers",
            "Penelope",
            "Penny",
            "Pepper",
            "Peppermint Patty",
            "Peppermiz",
            "Peppy",
            "Pepsi",
            "Percy",
            "Periwinkle",
            "Peter Cottontail",
            "Peter Pan",
            "Peter Rabbit",
            "Petey Rabbit",
            "Picasso",
            "Pig Pen",
            "Pinky",
            "Piper",
            "Pipkin",
            "Pirate",
            "Pluto",
            "Poke-a-dot",
            "Polly",
            "Pookie",
            "Pookie-poo",
            "Poppy",
            "Porsche",
            "Precious",
            "Prince",
            "Princess",
            "Princess Priscilla",
            "Priscilla",
            "Psycho",
            "Puddles",
            "Pugsli",
            "Puma",
            "Pumpernickle",
            "Pumpkin",
            "Puzzle",
            "Queen",
            "Quentin",
            "Quick Draw",
            "Quinn",
            "Rabbit",
            "Rabitat Tat",
            "Radar",
            "Ralph",
            "Ralphie",
            "Rambler",
            "Rambo",
            "Rascal",
            "Raven",
            "Red",
            "Reeses Pieces",
            "Rerun",
            "Rex",
            "Ricochet",
            "Riley",
            "Ringo",
            "Ripley",
            "Rizzo",
            "Robby Rabbit",
            "Robin",
            "Rocky",
            "Rodger Rabbit",
            "Romeo",
            "Roo",
            "Rory Rabbit",
            "Roscoe",
            "Rose",
            "Rosie",
            "Rowdy",
            "Roxie",
            "Roxy",
            "Ruby",
            "Rummy",
            "Runny Babbit",
            "Rupurt",
            "Rusty",
            "Sadie",
            "Safari",
            "Salsa",
            "Sam",
            "Sammy",
            "Sandy",
            "Santa",
            "Sasafras",
            "Sasha",
            "Sasparilla",
            "Sassy",
            "Scamper",
            "Scarecrow",
            "Scarlett",
            "Schnapps",
            "Scone MacBunny",
            "Scooby Do",
            "Scoota",
            "Scorpio",
            "Scotch",
            "Scrappy Too",
            "Scully",
            "Serenity",
            "Shadow",
            "Shasta",
            "Shelby",
            "Shep",
            "Sherlock Holmes",
            "Sherman",
            "Shimmerah",
            "Shining Star",
            "Shithead",
            "ShnuggleBunny",
            "Showoff",
            "Shy",
            "Silly",
            "Silver",
            "Simba",
            "Sir Hops Alot",
            "Sir.",
            "Sissy",
            "Sitting Bull",
            "Skippy",
            "Skittles",
            "Skywalker",
            "Slinky",
            "Smokey",
            "Smokey Jo",
            "Smores",
            "Snazzy",
            "Snicker doodles",
            "Snickers",
            "Sniffles",
            "Snoopy",
            "Snow cone",
            "Snow Drop",
            "Snow White",
            "Snowball",
            "Snowflake",
            "Snowy",
            "Snuggles",
            "Socks",
            "Softie Girl",
            "Solo",
            "Sophie",
            "Spade",
            "Spanky",
            "Sparkles",
            "Sparky",
            "Speedy",
            "Spice",
            "Spider-man",
            "Spike",
            "Spirit",
            "Splash",
            "Spock",
            "Spooky",
            "Sprinkles",
            "Sprite",
            "Spunky",
            "Sputnik",
            "Squiggles",
            "Squirt",
            "Starburst",
            "Starr",
            "Starsky",
            "Stew",
            "Stormin Norman",
            "Stormy",
            "Strawberry",
            "Stryker",
            "Stuart Little",
            "Sugar",
            "Sugar Baby",
            "Sunny",
            "Sunshine",
            "Super Bunny",
            "Sweet gum drops",
            "Sweet Heart",
            "Sweet Pea",
            "Sweetie",
            "Sweetie Pie",
            "Sylvester",
            "Tabu",
            "Taco",
            "Taffy",
            "Tali",
            "Tank",
            "Tarzan",
            "Tasmanian Devil",
            "Tazz",
            "Teddy",
            "Tex",
            "The Colonel",
            "Thumper",
            "Thumper Bumper",
            "Thunder",
            "Tibbar",
            "Tigger",
            "Tika",
            "Tilly",
            "Timber",
            "Tin Man",
            "Tinker Bell",
            "Tiny",
            "Tipper",
            "Titan",
            "Toast",
            "Tobey",
            "Toby",
            "Toffee",
            "Tootsie Roll",
            "Top Gun",
            "Topaz",
            "Topsy",
            "ToTo",
            "Trickster",
            "Trigger",
            "Trik Z",
            "Trix",
            "Trixie",
            "Trouble",
            "Tubby",
            "Tundra",
            "Turbo",
            "Tweety",
            "Twinkie",
            "Twinkles",
            "Twisted Whiskers",
            "Twister",
            "Twix",
            "Uncle Buck",
            "Vanilla",
            "Vegas",
            "Velvet",
            "Velveteen",
            "Venus",
            "Vin Diesel",
            "Vladimir",
            "Warden",
            "WeeBunBun",
            "Whinny",
            "Whiskers",
            "Whiskey",
            "Wiggles",
            "Wilbuhr",
            "Wild Boy",
            "Wild Er",
            "Wild Man",
            "Wild Thing",
            "Willow",
            "Winston",
            "Wonder Woman",
            "Woodstock",
            "Woody",
            "Worf",
            "Wuddly",
            "Xena",
            "Yahtzee",
            "Yankee",
            "Yo Yo",
            "Yoda",
            "Yogi",
            "Yoko",
            "Yosemite Sam",
            "Yoshi",
            "Zeus",
            "Ziggy",
            "Zoe",
            "Zorro",
            "Killer",
            "Punchface"


        });
    }
}



