/*****************************************************************************
 *      File:                   environDM.c
 *      Function:               Reponsible for the Cobolds
 *      Author(s):              Mizan@Nirvana
 *      Copyright:              Copyright (c) 2011 Mizan@Nirvana
 *                              All Rights Reserved.
 *      Source:                 2/2011
 *      Notes:
 *      Change History:
 ****************************************************************************/
#include "../definitions.h"
#include "/obj/ansi.h"

string *my_first_names;
string *my_last_names;
string *my_insults;

get() {
    return 0;
}
short() {
    return "A server named (cobold)";
}
id(str) {
    return str == "cobold" || str == "server";
}


string get_first_name() {
    return my_first_names[random(sizeof(my_first_names))];
}

string get_last_name() {
    return my_last_names[random(sizeof(my_last_names))];
}

string get_insult() {
    return my_insults[random(sizeof(my_insults))];
}

void reset(int arg)
{
    /* move ourselves home. */
    move_object(this_object(), DAEMON_HOME);

    if (!arg)
    {
        my_first_names = ( {
            "OLGA",
            "HELGA",
            "GERTRUDE",
            "BOB",
            "MINKA",
            "AGATHA",
            "CONSTANCE",
            "DELIA",
            "CORINNE",
            "EDITH",
            "ERNESTINE",
            "ELNORA",
            "ELANOR",
            "EUGENIA",
            "ELSPETH",
            "GLADYS",
            "HESTER",
            "ISADORA",
            "JUDITH",
            "LEONA",
            "MILLICENT",
            "MATILDA",
            "MEREDITH",
            "MYRTLE",
            "REGINA",
            "SIMONE",
            "RAMONA",
            "PRUDY",
            "WILHELMINA",
            "WILLA",
            "WINIFRED",

        });

        my_last_names = ( {
            "BITSTOMPER",
            "NIBBLER",
            "NIBBLES",
            "ACCESS",
            "ADD",
            "ADVANCING",
            "AFTER",
            "ALL",
            "ALPHABETIC",
            "ALSO",
            "ALTER",
            "ALTERNATE",
            "AND",
            "ARE",
            "AREA",
            "AREAS",
            "ASCENDING",
            "ASSIGN",
            "AT",
            "AUTHOR",
            "BEFORE",
            "BLANK",
            "BLOCK",
            "BOTTOM",
            "BY",
            "CALL",
            "CANCEL",
            "CD",
            "CF",
            "CH",
            "CHARACTER",
            "CHARACTERS",
            "CLOCK-UNITS",
            "CLOSE",
            "COBOL",
            "CODE",
            "CODE-SET",
            "COLLATING",
            "COLUMN",
            "COMMA",
            "COMMUNICATION",
            "COMP",
            "COMP-0",
            "COMPUTATIONAL-0",
            "CONFIGURATION",
            "CONTAINS",
            "CONTROL",
            "CONTROL-AREA",
            "COPY",
            "CORR",
            "CORRESPONDING",
            "COUNT",
            "CURRENCY",
            "DATA",
            "DATE",
            "DATE-COMPILED",
            "DATE-WRITTEN",
            "DAY",
            "DE",
            "DEBUG-CONTENTS",
            "DEBUG-ITEM",
            "DEBUG-LINE",
            "DEBUG-NAME",
            "DEBUG-SUB-1",
            "DEBUG-SUB-2",
            "DEBUG-SUB-3",
            "DEBUGGING",
            "DECIMAL-POINT",
            "DECLARATIVES",
            "DELETE",
            "DELIMITED",
            "DELIMITER",
            "DEPENDING",
            "DESCENDING",
            "DESTINATION",
            "DETAIL",
            "DISABLE",
            "DISPLAY",
            "DIVIDE",
            "DIVISION",
            "DOWN",
            "DUPLICATES",
            "DYNAMIC",
            "EGI",
            "ELSE",
            "EMI",
            "ENABLE",
            "END",
            "END-OF-PAGE",
            "ENTER",
            "ENVIRONMENT",
            "EOP",
            "EQUAL",
            "ERROR",
            "ESI",
            "EVERY",
            "EXCEPTION",
            "EXIT",
            "EXTEND",
            "FD",
            "FILE",
            "FILE-CONTROL",
            "FILLER",
            "FINAL",
            "FIRST",
            "FOOTING",
            "FOR",
            "FROM",
            "GENERATE",
            "GIVING",
            "GO",
            "GREATER",
            "GROUP",
            "HEADING",
            "HIGH-VALUE",
            "HIGH-VALUES",
            "I-O",
            "I-O-CONTROL",
            "IDENTIFICATION",
            "IF",
            "IN",
            "INDEX",
            "INDEXED",
            "INDICATE",
            "INITIAL",
            "INITIATE",
            "INPUT",
            "INPUT-OUTPUT",
            "INSPECT",
            "INSTALLATION",
            "INTO",
            "INVALID",
            "JUST",
            "JUSTIFIED",
            "KEY",
            "LABEL",
            "LAST",
            "LEADING",
            "LEFT",
            "LENGTH",
            "LESS",
            "LIMIT",
            "LIMITS",
            "LINAGE",
            "LINAGE-COUNTER",
            "LINE",
            "LINE-COUNTER",
            "LINES",
            "LINKAGE",
            "LOCK",
            "LOW-VALUE",
            "LOW-VALUES",
            "MEMORY",
            "MERGE",
            "MESSAGE",
            "MODE",
            "MODULES",
            "MORE-LABELS",
            "MULTIPLE",
            "MULTIPLY",
            "NATIVE",
            "NEGATIVE",
            "NEXT",
            "NO",
            "NOT",
            "NUMBER",
            "NUMERIC",
            "OBJECT-COMPUTER",
            "OCCURS",
            "OF",
            "OFF",
            "OMITTED",
            "ON",
            "OPEN",
            "OPTIONAL",
            "OR",
            "ORGANIZATION",
            "OUTPUT",
            "OVERFLOW",
            "PAGE",
            "PAGE-COUNTER",
            "PERFORM",
            "PF",
            "PH",
            "PIC",
            "PICTURE",
            "PLUS",
            "POINTER",
            "POSITION",
            "POSITIVE",
            "PRINTING",
            "PROCEDURE",
            "PROCEDURES",
            "PROCEED",
            "PROGRAM",
            "PROGRAM-ID",
            "QUEUE",
            "QUOTE",
            "QUOTES",
            "RANDOM",
            "RD",
            "READ",
            "RECEIVE",
            "RECORD",
            "RECORDS",
            "REDEFINES",
            "REEL",
            "REFERENCES",
            "RELATIVE",
            "RELEASE",
            "REMAINDER",
            "REMOVAL",
            "RENAMES",
            "REPLACING",
            "REPORT",
            "REPORTING",
            "REPORTS",
            "RERUN",
            "RESERVE",
            "RETURN",
            "REVERSED",
            "REWIND",
            "REWRITE",
            "RF",
            "RH",
            "RIGHT",
            "ROUNDED",
            "RUN",
            "SAME",
            "SD",
            "SEARCH",
            "SECTION",
            "SECURITY",
            "SEGMENT",
            "SEGMENT-LIMIT",
            "SELECT",
            "SEND",
            "SENTENCE",
            "SEPARATE",
            "SEQUENCE",
            "SEQUENTIAL",
            "SET",
            "SIGN",
            "SIZE",
            "SORT",
            "SORT-MERGE",
            "SOURCE",
            "SOURCE-COMPUTER",
            "SPACE",
            "SPACES",
            "SPECIAL-NAMES",
            "STANDARD",
            "STANDARD-1",
            "START",
            "STATUS",
            "STOP",
            "STRING",
            "SUB-QUEUE-1",
            "SUB-QUEUE-2",
            "SUB-QUEUE-3",
            "SUBTRACT",
            "SUM",
            "SUPER",
            "SYMBOLIC",
            "SYNC",
            "SYNCHRONIZED",
            "TALLYING",
            "TAPE",
            "TERMINAL",
            "TERMINATE",
            "TEXT",
            "THAN",
            "THROUGH",
            "THRU",
            "TIME",
            "TIMES",
            "TO",
            "TOP",
            "TRAILING",
            "TYPE",
            "UNIT",
            "UNSTRING",
            "UNTIL",
            "UP",
            "UPON",
            "USAGE",
            "USE",
            "USING",
            "VALUE",
            "VALUES",
            "VARYING",
            "WHEN",
            "WITH",
            "WORDS",
            "WORKING-STORAGE",
            "WRITE",
            "ZERO",
            "ZEROES",
            "ZEROS",

        });

        my_insults = ( {
            "DISPLAY \"What you problem, asshole?\"",
            "DISPLAY \"If you're looking for a fight, YOU GOT IT!\"",
            "DISPLAY \"You hit like a baby little Cobold!\"",
            "DISPLAY \"Oh, so you want to fight a LADY, do you?\"",
            "DISPLAY \"Dirty dumbasses!\"",
            "DISPLAY \"Got all that mouth but can't back it up?!\"",
            "DISPLAY \"You ugly looking fish-man thing!\"",
            "DISPLAY \"Staring in your face all I see is weakness!\"",
            "DISPLAY \"Go eat a bag of dicks!\"",
            "DISPLAY \"I'm going to beat your cheesy teeth in!\"",
            "DISPLAY \"Prepare to die, stinky-feet!\"",
            "DISPLAY \"Slimy grimy man-bitch! You die now!\"",
            "DISPLAY \"AAAAAUGH!\"",
            "DISPLAY \"Asshole, you in trouble now!\"",
            "ACCEPT PlayerIsAMoron",
            "ACCEPT PlayerSucks FROM DickBags",
            "PROCEDURE DIVISION",
        });
    }
}


