#include "../definitions.h"
string *my_weasel_names;
string *my_weasel_threats;

get() {
    return 0;
}
short() {
    return "A server named (weasel)";
}
id(str) {
    return str == "weasel" || str == "server";
}


string get_name() {
    return my_weasel_names[random(sizeof(my_weasel_names))];
}

string get_threat() {
    return my_weasel_threats[random(sizeof(my_weasel_threats))];
}

void reset(int arg)
{
    /* move ourselves home. */
    move_object(this_object(), DAEMON_HOME);

    if (!arg)
    {
        my_weasel_names = ( {
            "Hamster",
            "Weasel",
            "Guineapig",
            "Mousey",
            "Puppies",
            "Shoulders",
            "Dogpound",
            "Traintracks",
            "Railyard",
            "Rails",
            "Boxcar",
            "Rabbit",
            "Tabbit",
            "Tickler",
            "Tickles",
            "Measles",
            "Measleface",
            "Scabs",
            "Scabby",
            "Facescabber",
            "Growler",
            "Funkface",
            "Sweaty",
            "Neckripper",
            "Faceripper",
            "Repo",
            "Hotballs",
            "Shifty",
            "Wheezy",
            "Pheezy",
            "Sticky",
            "Numbnuts",
            "Giggles",
            "Hotpants",
            "Lefty",
            "Ace",
            "Potash",
            "Backslap",
            "Slappy",
            "Gonif",
            "Gonads",
            "Gonad",
            "Wiggles",
            "Gropey",
            "Fondles",
            "Fatface",
            "Mudbutt",
            "Bitey",
            "Facebiter",
            "Snitch",
            "Snitchy",
            "Hotplate",
            "Gaslight",
            "Crackmunchy",
            "Redface",
            "Redhole",
            "Pinkstink",
            "Pinkstinky",
            "Backdoor",
            "Palmslapper",
            "Crotchy",
            "Crotcho",
            "Crawley",
            "Cramps",
            "Rapeface",
            "Trigger",
            "Triggers",
            "Adobo",
            "Cardstealer",
            "Pastastealer",
            "Keystealer",
            "Sharpie",
            "Sharpy",
            "Sharpnuts",
            "Peltmaker",
            "Peltbiter",
            "Pelty",
            "Neckface",
            "Throaty",
            "Froggo",
            "Flunky",
            "Fartso",
            "Fatso",
            "Stinky",
            "Plasters",
            "Butters",
            "Muggers",
            "Grizzly",
            "Grizzles",
            "Grizzle",
            "Grumpy",
            "Groundhog",
            "Mudbeater",
            "Mudface",
            "Mudneck",
            "Asstrap",
            "Asstrappy",
            "Piles",
            "Craps",
            "Crappo",
            "Halfwit",
            "Stooge",
            "Blackfoot",
            "Lunkfoot",
            "Stoogelicker",
            "Pinky",
            "Farkbutter",
            "Frakface",
            "Digploppy",
            "Doppy",
            "Droppy",
            "Drippy",
            "Porkslapper",
            "Bugbiter",
            "Punkface",
            "Pesty",
            "Lockbiter",
            "Lockknocker",
            "Knocky",
            "Nipples",
            "Nipplebiter",
            "Teats",
            "Teatty",
            "Tipples",
            "Crapmuncher",
            "Crappie",
            "Crunko",
            "Crips",
            "Cripples",
            "Popples",
            "Fatcakes",
            "Fartsniffer",
            "Fatbiter",
            "Fatty",
            "Fatslicker",
            "Hotsauce",
            "Grits",
            "Gripper",
            "Grifty",
            "Grouchy",
            "Grufty",
            "Grunchy",
            "Kicker",
            "Clappy",
            "Claps",
            "Grunthog",
            "Crosseyes",
            "Wigglers",
            "Fingers",
            "Flakey",
            "Flakes",
            "Fartgagger",
            "Fuckles",
            "Chuckles",
            "Chompy",
            "Digfoot",
            "Diggy",
            "Diggers",
            "Snapjaw",
            "Snapface",
            "Snapneck",
            "Snaplicker",
            "Boxbiter",
            "Chewy",
            "Chewchompy",

        });

        my_weasel_threats = ({
            "You're in deep shit buddy!",
            "The hot oil has just hit the anus!",
            "You're in big trouble now!",
            "Here comes the big man on campus!",
            "You'll be like lipstick on a cat's ass when I'm done with you!",
            "It would be a real big shame for something to happen to your face.",
            "It would be a real big shame for something to happen to your gonads.",
            "It's time for my to give you an unsolicited finger to the anus!",
        });
    }
}

