#include "/players/eurale/defs.h"

  /*  Vampire Commands/Spells  */
#include "/players/eurale/VAMPIRES/lib/assess_mob.h"
#include "/players/eurale/VAMPIRES/lib/awaken.h"
#include "/players/eurale/VAMPIRES/lib/attack_backhand.h"
#include "/players/eurale/VAMPIRES/lib/attack_damn.h"
#include "/players/eurale/VAMPIRES/lib/attack_demon.h"
#include "/players/eurale/VAMPIRES/lib/attack_grasp.h"
#include "/players/eurale/VAMPIRES/lib/attack_scratch.h"
#include "/players/eurale/VAMPIRES/lib/bat_alarm.h"
#include "/players/eurale/VAMPIRES/lib/bat_message.h"
#include "/players/eurale/VAMPIRES/lib/batsell_item.h"
#include "/players/eurale/VAMPIRES/lib/benergy.h"
#include "/players/eurale/VAMPIRES/lib/bite_player.h"
#include "/players/eurale/VAMPIRES/lib/call_wolf.h"
#include "/players/eurale/VAMPIRES/lib/calm_fighters.h"
#include "/players/eurale/VAMPIRES/lib/cancel_summons.h"
#include "/players/eurale/VAMPIRES/lib/cause_fear.h"
#include "/players/eurale/VAMPIRES/lib/check_player.h"
#include "/players/eurale/VAMPIRES/lib/create_form.h"
#include "/players/eurale/VAMPIRES/lib/cure_disease.h"
#include "/players/eurale/VAMPIRES/lib/dismiss_bat.h"
#include "/players/eurale/VAMPIRES/lib/donate_item.h"
#include "/players/eurale/VAMPIRES/lib/drain_corpse.h"
#include "/players/eurale/VAMPIRES/lib/emotes.h"
#include "/players/eurale/VAMPIRES/lib/emotes2.h"
#include "/players/eurale/VAMPIRES/lib/emotes3.h"
#include "/players/eurale/VAMPIRES/lib/expell_player.h"
#include "/players/eurale/VAMPIRES/lib/fix_heart.h"
#include "/players/eurale/VAMPIRES/lib/go_guild.h"
#include "/players/eurale/VAMPIRES/lib/guild_help.h"
#include "/players/eurale/VAMPIRES/lib/infuse_sp.h"
#include "/players/eurale/VAMPIRES/lib/leave_guild.h"
#include "/players/eurale/VAMPIRES/lib/levitate.h"
#include "/players/eurale/VAMPIRES/lib/no_game_spls.h"
#include "/players/eurale/VAMPIRES/lib/obit_list.h"
#include "/players/eurale/VAMPIRES/lib/regen.h"
#include "/players/eurale/VAMPIRES/lib/scan_wolf.h"
#include "/players/eurale/VAMPIRES/lib/sharpen_fangs.h"
#include "/players/eurale/VAMPIRES/lib/shift_hp.h"
#include "/players/eurale/VAMPIRES/lib/show_item.h"
#include "/players/eurale/VAMPIRES/lib/show_inven.h"
/*  unnecessary now
#include "/players/eurale/VAMPIRES/lib/show_player.h"
*/
#include "/players/eurale/VAMPIRES/lib/show_score.h"
#include "/players/eurale/VAMPIRES/lib/show_vamps.h"
#include "/players/eurale/VAMPIRES/lib/show_vamps2.h"
#include "/players/eurale/VAMPIRES/lib/show_whopk.h"
#include "/players/eurale/VAMPIRES/lib/show_whov.h"
#include "/players/eurale/VAMPIRES/lib/summon.h"
#include "/players/eurale/VAMPIRES/lib/telepathy.h"
#include "/players/eurale/VAMPIRES/lib/telepathyfeel.h"
#include "/players/eurale/VAMPIRES/lib/transfer_item.h"
#include "/players/eurale/VAMPIRES/lib/vamp_demote.h"
#include "/players/eurale/VAMPIRES/lib/vamp_promote.h"
#include "/players/eurale/VAMPIRES/lib/vamp_quit.h"
#include "/players/eurale/VAMPIRES/lib/vamp_save.h"
#include "/players/eurale/VAMPIRES/lib/vemove.h"
#include "/players/eurale/VAMPIRES/lib/veplace.h"

  /*  Adjust field to display 'n' chars for formatted display  */
LADJUST(str,n) { return extract(str+"                    ",0,n-1); }
