#include "/players/feldegast/defines.h"
#define PATH "/players/feldegast/darkcity/"
#define MYROOM "/players/feldegast/std/room.c"
#define KEY "strangerkeyid312654"
#define STRANGER "/players/feldegast/darkcity/Npc/stranger.c"
