/* aliases */
#define me     this_object()
#define owner  environment(me)
#define QRN    query_real_name()
#define ENV    environment
#define CAP    capitalize
#define TO me
#define FN file_name
#define base_name basename
#define TP this_player()
#define CALLER caller()
#define QN query_name()
#define QL query_level()
#define QXL query_extra_level()
#define QXP query_exp()
#define QGR query_guild_rank()
#define QHP query_hp()
#define QSP query_sp()
#define QMHP query_mhp()
#define QMSP query_msp()
#define HP hit_player
#define MP move_player
#define MO move_object
#define CO clone_object
#define HS heal_self
#define AHP add_hit_point
#define ASP add_spell_point
