#define MASTER  "/players/vertebraker/classic/undead/master"
#define CMDDIR "/players/vertebraker/classic/undead/cmds/"
#define MAINSAVE "players/vertebraker/classic/undead/save/"
#define OBJPATH "/players/vertebraker/classic/undead/life"
#define GUILDNAME "Undead"
