#define BASE "/players/snow/chaos/base.c"
#define TP this_player()
#define TO this_object()
#define TPN CAP(TP->query_name())
#define TPRN TP->query_real_name()
#define GEN TP->query_possessive()
#define CAP capitalize
#define PRE present
#define ENV environment
#define CO call_other
#define MP move_player
#define MO move_object
#define TE tell_object
#define TR tell_room
#define RE return 1
#define WANDER 400
#define APPEAR 45
#define C1 "/players/snow/chaos/r1.c"
#define C2 "/players/snow/chaos/r2.c"
#define C3 "/players/snow/chaos/r3.c"
#define C4 "/players/snow/chaos/r4.c"
#define C5 "/players/snow/chaos/r5.c"
#define C6 "/players/snow/chaos/r6.c"
#define C7 "/players/snow/chaos/r7.c"
#define C8 "/players/snow/chaos/r8.c"
#define C9 "/players/snow/chaos/r9.c"
#define CPORT "/players/snow/chaos/port.c"
#define BLOBM "/players/snow/chaos/mon/blob.c"
#define CRABM "/players/snow/chaos/mon/crab.c"
#define CRAWFISHM "/players/snow/chaos/mon/crawfish.c"
#define EFREETIM "/players/snow/chaos/mon/efreeti.c"
#define QUICKM "/players/snow/chaos/mon/quickling.c"
#define STIRGEM "/players/snow/chaos/mon/stirge.c"
#define SPHINXM "/players/snow/chaos/mon/sphinx.c"
#define CATERM "/players/snow/chaos/mon/cater.c"
#define HUNTERM "/players/snow/chaos/mon/hunter.c"
