/*  Eurale's Wiztool  */

#include "/players/eurale/closed/HLP/aset.h"
#include "/players/eurale/closed/HLP/attrib.h"
#include "/players/eurale/closed/HLP/calm.h"
#include "/players/eurale/closed/HLP/commands.h"
#include "/players/eurale/closed/HLP/church.h"
#include "/players/eurale/closed/HLP/filer.h"
#include "/players/eurale/closed/HLP/finger.h"
#include "/players/eurale/closed/HLP/freeze.h"
#include "/players/eurale/closed/HLP/garble.h"
#include "/players/eurale/closed/HLP/hand.h"
#include "/players/eurale/closed/HLP/heal.h"
#include "/players/eurale/closed/HLP/ibag.h"
#include "/players/eurale/closed/HLP/idest.h"
#include "/players/eurale/closed/HLP/inven.h"
#include "/players/eurale/closed/HLP/inven_room.h"
#include "/players/eurale/closed/HLP/nset.h"
#include "/players/eurale/closed/HLP/register.h"
#include "/players/eurale/closed/HLP/sset.h"
#include "/players/eurale/closed/HLP/strep.h"
#include "/players/eurale/closed/HLP/teller.h"
#include "/players/eurale/closed/HLP/unguild.h"
#include "/players/eurale/closed/HLP/view.h"
