#define BASE "/players/snow/dark/base.c"
#define TP this_player()
#define TO this_object()
#define TPN CAP(TP->query_name())
#define TPRN TP->query_real_name()
#define GEN TP->query_possessive()
#define CAP capitalize
#define PRE present
#define ENV environment
#define CO call_other
#define MP move_player
#define MO move_object
#define TE tell_object
#define TR tell_room
#define RE return 1
#define WANDER 400
#define APPEAR 45
#define C1 "/players/snow/dark/rooms/r1.c"
#define C2 "/players/snow/dark/rooms/r2.c"
#define C3 "/players/snow/dark/rooms/r3.c"
#define C4 "/players/snow/dark/rooms/r4.c"
#define C5 "/players/snow/dark/rooms/r5.c"
#define C6 "/players/snow/dark/rooms/r6.c"
#define C7 "/players/snow/dark/rooms/r7.c"
#define C8 "/players/snow/dark/rooms/r8.c"
#define C9 "/players/snow/dark/rooms/r9.c"
#define CPORT "/players/snow/dark/port.c"
#define SHADM "/players/snow/dark/mons/shad"
#define CREEM "/players/snow/dark/mons/creeper"
#define SPINM "/players/snow/dark/mons/spiny"
#define SPECM "/players/snow/dark/mons/spectre"
#define VAMPM "/players/snow/dark/mons/vampire"
#define SKELM "/players/snow/dark/mons/skeleton"
#define ZOMBM "/players/snow/dark/mons/zombie"
#define ASSAM "/players/snow/dark/mons/assassin"
