animal_set_up() {
string aaa,aba,aca,ada,aea,afa,aga,aha,aia,aja;
string aab,abb,acb,adb,aeb,afb,agb,ahb,aib,ajb;
string baa,bba,bca,bda,bea,bfa,bga,bha,bia,bja;
string bab,bbb,bcb,bdb,beb,bfb,bgb,bhb,bib,bjb;
int za,ya,xa,wa,va,ua,ta,sa,ra,qa;
int zb,yb,xb,wb,vb,uv,tb,sb,rb,qb;
 animal= ({"wolf"}); 
 an_short = ({"A wolf"});
 an_level = ({10});
 an_hp = ({10});
 an_wc = ({10});
 an_ac = ({10});
 an_chat_chance = ({10});
 an_chat_att_chance = ({10});
 aaa = ({""});
 aba = ({""});
 aca = ({""});
 ada = ({""});
 aea = ({""});
 afa = ({""});
 aga = ({""});
 aha = ({""});
 aia = ({""});
 aja = ({""});
 aab = ({""});
 abb = ({""});
 acb = ({""});
 adb = ({""});
 aeb = ({""});
 afb = ({""});
 agb = ({""});
 ahb = ({""});
 aib = ({""});
 ajb = ({""});
 baa = ({""});
 bba = ({""});
 bca = ({""});
 bda = ({""});
 bea = ({""});
 bfa = ({""});
 bha = ({""});
 bia = ({""});
 bja = ({""});
 bab = ({""});
 bbb = ({""});
 bcb = ({""});
 bdb = ({""});
 beb = ({""});
 bfb = ({""});
 bgb = ({""});
 bhb = ({""});
 bib = ({""});
 bjb = ({""});
 za = ({0});
 ya = ({0});
 xa = ({0});
 wa = ({0});
 va = ({0});
 ua = ({0});
 ta = ({0});
 sa = ({0});
 ra = ({0});
 qa = ({0});
 zb = ({0});
 yb = ({0});
 xb = ({0});
 wb = ({0});
 vb = ({0});
 ub = ({0});
 tb = ({0});
 sb = ({0});
 rb = ({0});
 qb = ({0});
 an_chance = ({za,ya,xa,wa,va,ua,ta,sa,ra,qa});
 an_dam = ({zb,yb,xb,wb,vb,uv,tb,sb,rb,qb});
 an_tell = ({aaa,aba,aca,ada,aea,afa,aga,aha,aia,aja});
 an_mess = ({aab,abb,acb,adb,aeb,afb,agb,ahb,aib,ajb});
 an_chat = ({baa,bba,bca,bda,bea,bfa,bga,bha,bia,bja});
 an_att_chat = ({bab,bbb,bcb,bdb,beb,bfb,bgb,bhb,bib,bjb});
}