c() {
command("cd /players/pain",this_player());
return 1;}
cc() {
command("cd /players/pain/closed",this_player());
return 1;}
CASTLE() {
command("cd /players/pain/CASTLE",this_player());
return 1;}
cm() {
command("cd /players/pain/closed/monsters",this_player());
return 1;}
ca() {
command("cd /players/pain/closed/armor",this_player());
return 1;}
cw() {
command("cd /players/pain/closed/weapons",this_player());
return 1;}
ci() {
command("cd /players/pain/closed/items",this_player());
return 1;}