
inherit "room/room";

init() {
add_action("down", "down");
add_action("north", "north");
}
down() {
this_player()->move_player("exits the chamber#players/cyrex/quest/rchamber");
return 1;
}
north() {
if(present("master")) {
write("An unknown force prevents you from moving further in that direction.\n");
command("think",this_player());
return 1;
}
this_player()->move_player("enters the inner chamber#players/cyrex/quest/incha");
return 1;
}
reset(arg) {
 if(!present("master1")) {
   move_object(clone_object("players/cyrex/quest/master1"), this_object());
 }
 if(!present("master2")) {
   move_object(clone_object("players/cyrex/quest/master2"), this_object());
 }
if(!present("master3")) {
  move_object(clone_object("players/cyrex/quest/master3"), this_object());
}
  if(!arg) {
  set_light(1);
  short_desc = "Master Chamber";
  long_desc =
 "This is the main chamber of the Robotech Masters. All creations they have\n"+
 "made is done here. In the center of the room, you see the three Masters\n"+
 "hovering. They seem to be somewhat wounded, but instincts tells you that\n"+
 "still you should not under estimate their powers and strength. You notice\n"+
 "on the floor several large Invid tracks leading north. How strange.\n";
  no_exits = 1;
  property = ({"NT"});
  items = ({"force",
            "The force seems to be generated by the masters."});
  }
}
