#define LIB "/players/vital/closed/lib/"

#define circumfrence(a0) call_other(LIB + "circle.c", "circumfrence", a0)
#define circle_area(a0) call_other(LIB + "circle.c", "circle_area", a0)
#define yes_no(a0) call_other(LIB + "yes_no.c", "main", a0)
#define toggle_on(a0) call_other(LIB + "toggle.c", "toggle_on", a0)
#define toggle_off(a0) call_other(LIB + "toggle.c", "toggle_off", a0)
#define deconstruct_mapping(a0) call_other(LIB + "deconstruct_mapping.c", "deconstruct_mapping", a0)
#define fix_path(a0) call_other(LIB + "fix_path.c", "fix_path", a0)
#define format_time(a0) call_other(LIB + "format_time.c", "format_time", a0)
#define get_files(a0) call_other(LIB + "get_files.c", "get_files", a0)
#define get_prototype(a0,a1,a2) call_other(LIB + "get_prototype.c", "get_prototype", a0,a1,a2)
#define get_root(a0) call_other(LIB + "get_root.c", "get_root", a0)
#define has_member(a0,a1) call_other(LIB + "has_member.c", "has_member", a0,a1)
#define reconstruct_mapping(a0) call_other(LIB + "reconstruct_mapping.c", "reconstruct_mapping", a0)
#define rewrap_file(a0,a1) call_other(LIB + "rewrap_file.c", "rewrap_file", a0,a1)
#define random_color() call_other(LIB + "random_color.c", "random_color")
#define m_indices(a0) call_other(LIB + "m_efuns.c", "m_indices",a0)
#define vreconstruct_mapping(a0) call_other(LIB + "m_efuns.c", "reconstruct_mapping",a0)
#define vdeconstruct_mapping(a0) call_other(LIB + "m_efuns.c", "deconstruct_mapping",a0)
#define member_mapping(a0,a1) call_other(LIB + "m_efuns.c", "member",a0,a1)
#define m_delete(a0,a1) call_other(LIB + "m_efuns.c", "m_delete",a0,a1)
#define delete_mapping(a0,a1) call_other(LIB + "m_efuns.c", "m_delete",a0,a1)
#define m_values(a0) call_other(LIB + "m_efuns.c", "m_values",a0)
#define color_pad(a0,a1) call_other(LIB + "m_efuns.c", "colour_pad",a0,a1)
#define text_contains(a0,a1) call_other(LIB + "m_efuns.c", "text_contains",a0,a1)
#define skip_spaces(a0) call_other(LIB + "skip_spaces.c", "skip_spaces",a0)
#define remove_spaces(a0) call_other(LIB + "skip_spaces.c", "remove_spaces",a0)
#define dump_mapping(a0) call_other(LIB + "dump_mapping.c", "dump_mapping",a0)

