/* Black Circle Mage guild object.
   Version 1.1.0 [beta]
   Originally coded by Glaendor
   Updated by Fred [4.13.03]
*/
 
#include "defs.h"
#include "homedir/variables.h"
#include "homedir/id.h"
#include "homedir/reset.h"
#include "homedir/init.h"
#include "homedir/heartbeat.h"
#include "homedir/weapon.h"
#include "lib/bede.c"
#include "lib/blast.c"
#include "lib/cc.c"
#include "lib/ce.c"
#include "lib/circle.c"
#include "lib/coat.c"
#include "lib/curse.c"
#include "lib/dart.c"
#include "lib/demise.c"
#include "lib/deathknight.c"
#include "lib/disrupt.c"
#include "lib/dragon.c"
#include "lib/drain.c"
#include "lib/flame.c"
#include "lib/fog.c"
#include "lib/freeze.c"
#include "lib/ghoul.c"
#include "lib/heal.c"
#include "lib/home.c"
#include "lib/obillusion.c"
#include "lib/pillusion.c"
#include "lib/lich.c"
#include "lib/memorize.c"
#include "lib/midas.c"
#include "lib/mreport.c"
#include "lib/mrestore.c"
#include "lib/msave.c"
#include "lib/mupdate.c"
#include "lib/quit.c"
#include "lib/recall.c"
#include "lib/revert.c"
#include "lib/risk.c"
#include "lib/say.c"
#include "lib/score.c"
#include "lib/score2.c"
#include "lib/ssave.c"
#include "lib/stat_check.c"
#include "lib/tell.c"
#include "lib/title.c"
#include "lib/uncurse.c"
#include "lib/vitalize.c"
#include "lib/xfer.c"
#include "lib/drakyr.c"

