#define BA "/players/languilen/guild/mob/"
#define ROOM   BA  + "rooms/"
#define MON    BA  + "mons/"
#define OBJ    BA  + "objs/"
#define WEP    OBJ + "weps/"
#define ARM    OBJ + "arms/"
#define MYENTRANCE "/players/languilen/module.c"
