tell_room(ENV(TO),"                                                      .                          \n");
tell_room(ENV(TO),"                                                     `s                          \n");
tell_room(ENV(TO),"                                                     o/                          \n");
tell_room(ENV(TO),"                                                     d-                          \n");
tell_room(ENV(TO),"                                                    `M:                          \n");
tell_room(ENV(TO),"                                                .,  `Ms                          \n");
tell_room(ENV(TO),"                                                `y` `mh                          \n");
tell_room(ENV(TO),"                     ``                          yo  yM-                         \n");
tell_room(ENV(TO),"                     `o.                         dh  :Mh`     '                  \n");
tell_room(ENV(TO),"                      :m.                       -Mh  `dMs    `/`                 \n");
tell_room(ENV(TO),"                      -Nd   -           ,      `dM/   :MMs    -y`                \n");
tell_room(ENV(TO),"            ,         -MM: -o           o      +Md     yMM+    hy                \n");
tell_room(ENV(TO),"            o`        /MM: /d           m      mMy     .NMN:   oN.  :            \n");
tell_room(ENV(TO),"           .N         yMm  :M/          N.    -NMd      hMMm   hN- `o            \n");
tell_room(ENV(TO),"           /N        -NM+   yN/`     /` No    .NMMo`   -NMMM: `Nm   m-           \n");
tell_room(ENV(TO),"       `   +M       `dMm`   `sNh:    +o oN-    hMMMdsshNMMMM+ oMo   om+`         \n");
tell_room(ENV(TO),"       .o` /M/      yMMy      :mMs`  -d `dm:   .NMMMMMMMMMMM+.NM.    /Nd.        \n");
tell_room(ENV(TO),"        No `mm-    -MMMo       /MMo  /h  .dNs`  :NMMMMMMMMMM.-MM`     hMd`       \n");
tell_room(ENV(TO),"        Nm  /Nm/   /MMMy       .MMN.`m/   `mMd.  -dMMMMMMMMy -MMy-```.mMM: .+    \n");
tell_room(ENV(TO),"       :My   +MN/  /MMMNo.`  `.yMMM-yM:    yMMm.  .hMMMMMMm. `dMMMmhhNMMN. d+    \n");
tell_room(ENV(TO),"       hM+    dMN. .NMMMMNdhydNMMMM.NMs` `-NMMMs   `dMMMMN-   :MMMMMMMMM+ :M+    \n");
tell_room(ENV(TO),"      -MM+    hMM+  yMMMMMMMMMMMMNs hMMdyhNMMMMd    -MMMMo     hMMMMMMN/  .Nd`   \n");
tell_room(ENV(TO),"   ,  +MMy` `/NMM+  `dMMMMMMMMMMN/  -mMMMMMMMMM+    `MMMM:     +MMMMMN:    +Mh`  \n");
tell_room(ENV(TO),"   -  /MMMdydMMMN.   -NMMMMMMMMM-    .hMMMMMMN+     oMMMMo     yMMMMMd      oMd` \n");
tell_room(ENV(TO),"   o: -MMMMMMMMM+     hMMMMMMMMy      :MMMMMMm`    /MMMMMNs/-/yMMMMMMd      :MMh \n");
tell_room(ENV(TO),"   ds  hMMMMMMMM-    `dMMMMMMMMh`     sMMMMMMMmo:/hMMMMMMMMMMMMMMMMMMMo`   .dMMM/\n");
tell_room(ENV(TO),"  :Ms  :MMMMMMMMm+..:hMMMMMMMMMMh:../hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdddMMMMMo\n");
tell_room(ENV(TO)," .mMh` /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+\n");
tell_room(ENV(TO),"`mMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm`\n");
tell_room(ENV(TO),"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss. \n");