#include "/players/snow/guild/body/body_clean.h"
#include "/players/snow/guild/body/digest.h"
#include "/players/snow/guild/body/cyborg_get.h"
#include "/players/snow/guild/body/cyborg_look.h"
#include "/players/snow/guild/body/cyborg_put.h"
#include "/players/snow/guild/body/run.h"
#include "/players/snow/guild/body/cyborg_wield.h"
