#include "/players/anshar/sage/lib/shelp.h"
#include "/players/anshar/sage/lib/shome.h"
#include "/players/anshar/sage/lib/stitle.h"
#include "/players/anshar/sage/lib/schat.h"
#include "/players/anshar/sage/lib/sc.h"
